### ISSUE TITLE
Problem using identityserver4 Login Page

### ISSUE THREAD

**Issue by eflorespalma** [VahidN/DNTCaptcha.Core#10]
Is There a way to refresh de button vía javascript.

**Comment by VahidN** [comment]
This library uses unobtrusive Ajax library for the refresh button. Make sure you have included its related scripts too. [That's all you need to do](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.TestWebApp/bower.json#L9).
