### ISSUE TITLE
noise problem 

### ISSUE THREAD

**Issue by Erfan1398** [VahidN/DNTCaptcha.Core#107]
# Summary of the issue
سلام وحید جان ، شما که زحمت کشیدی این نویزشم درست کن لطفا ، اصلا قابل خوندن نیست 
بعد من چطور میتونم المانا رو جدا گانه لیوت کنم ؟ مثلا جایگذاری پیام خطا یا دکمه رفرش رو عوض کنم؟

## Environment

```
DNTCaptcha.Core version: 
.NET Core SDK version:  .net 5
IDE: 
```

## Example code/Steps to reproduce:

```
paste your core code
```

## Output:

```
Exception message:
Full Stack trace:
```

**Comment by VahidN** [comment]
<div dir="rtl">

[ asp-text-box-template](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.TestWebApp/Views/Home/_LoginFormBody.cshtml#L51) را بايد سفارشي سازي كنيد

**Comment by Erfan1398** [comment]
چجوری سفارشی کنم ؟ میشه یه مثال بدی چون آیدی الماناشو نمیدونم

**Comment by VahidN** [comment]
<div dir="rtl">

بيشتر از اين سفارشي سازي ندارد؛ چون اين المان‌ها خيلي خاص با [ويژگي‌هاي مشخصي](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.Core/DNTCaptchaTagHelper.cs#L221) توليد مي‌شوند كه برنامه بايد به صورت خودكار توليد كند
البته يك نمونه استفاده‌ي آزاد از اين امكانات در حالت اي‌جكسي [اينجا هست](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.TestApiApp/wwwroot/index.html#L24)

**Comment by Erfan1398** [comment]
ممنون ازپشتیبانیتون ، البته من دقیقا به چیزی که میخواستم نرسیدم ولی مشکل
حادی نیست ،  فقط یه چیز دیگه این دکمه رفرش کار نمینه

**Comment by VahidN** [comment]
<div dir="rtl">

[refresh button](https://github.com/VahidN/DNTCaptcha.Core/blob/master/README.md) را در راهنماي آن جستجو كنيد.

**Comment by Erfan1398** [comment]
دستت درد نکنه ، بازم ممنون از پاسخگویی ، نویزشم اوکی کنی واقعا خوب میشه ولی
همین الانم من اگه بشه میرم کردیت میدم بهش مرسی 🙏
