### ISSUE TITLE
Alpha Numeric Captcha

### ISSUE THREAD

**Issue by Parinaz-rh** [VahidN/DNTCaptcha.Core#109]
Hi
Is it possible to change the display mode of captcha to alpha numeric?
If not would you please add this option to display modes.
Thanks in advance

**Comment by VahidN** [comment]
No. This is not a general purpose captcha. It was designed to show `NumberToWord` initially and now it has 3 more modes about numbers only. This is a numbers only captcha and I have no intention to develop it further.
