### ISSUE TITLE
Captcha not work under nginx proxy or https

### ISSUE THREAD

**Issue by jackhhh** [VahidN/DNTCaptcha.Core#11]
```
`info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
Executing action method DNTCaptcha.Core.DNTCaptchaImageController.Show (DNTCaptcha.Core) with arguments (CfDJ8AUyVhOCtYhBqsBayGrsMEg6ZEKonj8Yu4zyLjktNB8GB1aWxuLw9zhe3cuRfPfMiOi/F2sTu/8TXeYBrtMG42XJ2TPsiPDrmOU19aetv6kfg+YXpQu7Jy3vFg1RG3I9gY0ugsP2zH5Cb5uu15Zr50A=, 636275045063773290, black, #ccc, 20, Tahoma) - ModelState is Valid
info: Microsoft.AspNetCore.Mvc.StatusCodeResult[1]
Executing HttpStatusCodeResult, setting HTTP status code 400
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
Executed action DNTCaptcha.Core.DNTCaptchaImageController.Show (DNTCaptcha.Core) in 0.3593ms
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
Executing action method IdentityServerWithIdentityCore.Controllers.ErrorController.Index (IdentityServerWithIdentityCore) with arguments (400) - ModelState is Valid
fail: IdentityServerWithIdentityCore.Controllers.ErrorController[0]
Error 400 for GET /DNTCaptchaImage/Show
```

I run my project in a docker container, if I bind a domain by nginx then use proxy_pass forward to the container, or add SSL through CDN service, the captcha will return 400 error. Maybe it results from ports or something else?

**Comment by VahidN** [comment]
Have you installed the `libgdiplus` dependencies?
```
RUN apt-get update                    
RUN apt-get install -y libgdiplus  
```

**Comment by jackhhh** [comment]
Yes I have installed.
You can see [http://res.bitnp.net/en-us/reservation/create](url) & [https://res.bitnp.net/en-us/reservation/create](url)
The captcha can display in http but cannot in https

**Comment by VahidN** [comment]
I think you are not using the last version (V 1.4). In this version, the full [Request.Scheme](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.Core/DNTCaptchaTagHelper.cs#L169) will be added to the final `/DNTCaptchaImage/Show` URL.

**Comment by VahidN** [comment]
`HTTP Error 400` means [return BadRequest();](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.Core/DNTCaptchaImageController.cs#L136). Try V1.4, and debug `return BadRequest();`s.
