### ISSUE TITLE
Validation of captcha doens't work while code is correct

### ISSUE THREAD

**Issue by timgoeij** [VahidN/DNTCaptcha.Core#110]
# Summary of the issue
Hi, I' am trying out your webapi example, but I have a problem with the validation of the captcha it only gives false while the input of the code is correct. I tried both validation methods with the validationservice and the attributes. Is it possible that validation doesn't work because the html file doesn't live in the wwwroot folder or runs on a server? I run the file now from a local folder.

## Environment

```
DNTCaptcha.Core version: 3.7.0
.NET Core SDK version: 3.1
IDE: Visual studio community 2019
```

## Example code/Steps to reproduce:

```
[HttpGet("dnt")]
        [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true, Duration = 0)]
        public ActionResult<DNTCaptchaApiResponse> CreateCaptcha()
        {
            return _apiProvider.CreateDNTCaptcha(new DNTCaptchaTagHelperHtmlAttributes
            {
                BackColor = "#f7f3f3",
                FontName = "Tahoma",
                FontSize = 18,
                ForeColor = "#111111",
                Language = Language.English,
                DisplayMode = DisplayMode.ShowDigits,
                Max = 90,
                Min = 1
            });
        }

        /*[HttpPost("dnt")]
        [ValidateDNTCaptcha(ErrorMessage = "Please enter the security code as number.",
            CaptchaGeneratorLanguage = Language.English,
            CaptchaGeneratorDisplayMode = DisplayMode.ShowDigits)]
        public IActionResult Login([FromForm] UserModel data)
        {
            if (ModelState.IsValid)
                return RedirectToAction("Login", "User", data);

            return BadRequest(ModelState);
        }*/

        [HttpPost("dnt")]
        public IActionResult Login([FromForm] UserModel data)
        {
            if(!_validatorService.HasRequestValidCaptchaEntry(Language.English, DisplayMode.ShowDigits))
            {
                ModelState.AddModelError(_captchaOptions.CaptchaComponent.CaptchaInputName, "Please enter the security code as a number.");
                return BadRequest(ModelState);
            }

             return RedirectToAction("Login", "User", data);
        }`

services.AddDNTCaptcha(options =>
            {
                options.UseCookieStorageProvider()
                .ShowThousandsSeparators(false)
                .WithEncryptionKey("my code");
            });`
```
front-end code is the same as in your example

## Output:

```
Exception message:
Full Stack trace:
```

**Comment by VahidN** [comment]
Press `F12` and checkout the network tab of the developers tools of your browser. Do you see any errors? Also checkout the console/debug tab of your VS to see the server side errors.

**Comment by timgoeij** [comment]
Both in the developer tools in the browser and the console/debug tab of VS I don't see any errors. In the developer tools only the badrequest because the validation don't work

**Comment by timgoeij** [comment]
I am using cores at the moment, is that maybe the problem?

**Comment by VahidN** [comment]
`BadRequest`s have a response body. You can find some info at there. Also this library logs everything using the built-in ILogger. Try to set the log-level to debug to see them.

**Comment by timgoeij** [comment]
In the response body I found only the errors of the ModelState and in the logs I found the following:

DNTCaptcha.Core.CookieCaptchaStorageProvider: Debug: Couldn't find the captcha cookie in the request.
DNTCaptcha.Core.DNTCaptchaValidatorService: Debug: isValidCookie:: cookieValue IsNullOrWhiteSpace.

**Comment by VahidN** [comment]
There has been a lot of changes regarding sending cookies to other domains recently in all of the browsers. If you are using CORS, use `UseSessionStorageProvider` or `UseMemoryCacheStorageProvider` instead of the `UseCookieStorageProvider` .
