### ISSUE TITLE
امکان حذف دکمه به روزرسانی کد امنیتی

### ISSUE THREAD

**Issue by ni-fara** [VahidN/DNTCaptcha.Core#111]
سلام مدتی است که بسیاری از کتابخانه هایی که از
jquery
استفاده میکردند در حال حذف این کتابخانه از کدهایشان و استفاده از
javascript
محظ در کدهایشان هستند، مانند کتابخانه
bootstrap5.
من هم به جهت کاهش حجم صفحات قصد حذف کتابخانه
jquery
و طبیعتا کتابخانه هایی که به آن وابسته هستند مانند
jquery-ajax-unobtrusive
رو دارم، اما در صورت حذف کتابخانه های ذکر شده دکمه به روز رسانی کد امنیتی ایجاد خطا مینماید.
در صورت امکان، تنظیماتی جهت حذف و عدم نمایش دکمه به روز رسانی کد امنیتی قرار دهید.

**Comment by VahidN** [comment]
Try V 3.8.

**Comment by ni-fara** [comment]
متشکر
