### ISSUE TITLE
نویز بسیار زیاد در ورژن 4

### ISSUE THREAD

**Issue by nikkhoo63** [VahidN/DNTCaptcha.Core#114]
سلام 
نسخه 4.0.0 رو که نصب کردم، در ۸۰ درصد مواقع نویز اینقدر زیاد می باشد که متن ناخوانا می باشد. درصورت امکان نویز را کمتر کنید
ممنون از زحمات شما

**Comment by VahidN** [comment]
<div dir="rtl">

مشكلي ندارد و تا اين حد معمول هست:
![cpta](https://user-images.githubusercontent.com/766010/126032105-86d8fad8-baea-4d33-8117-212b8088f529.png)
