### ISSUE TITLE
Illegible image due to excessive noise

### ISSUE THREAD

**Issue by senchden** [VahidN/DNTCaptcha.Core#115]
Hello.
When using certain CAPTCHA modes, most images are completely illegible due to excessive noise. Please bring back 'asp-use-noise' attribute and/or allow us to configure noise level. Relates to https://github.com/VahidN/DNTCaptcha.Core/issues/114
Tested with version 4.0.0

See enclosed images:
![image](https://user-images.githubusercontent.com/31250983/126495818-e595cd1f-9fc6-4a2f-adee-de6133b5f3d4.png)

![image](https://user-images.githubusercontent.com/31250983/126495879-536090b9-37eb-46ce-b961-3dfebd050b27.png)
![image](https://user-images.githubusercontent.com/31250983/126495920-75bebbf7-b5b2-490f-99b1-899d5bfe22bb.png)

Thank you.

**Comment by VahidN** [comment]
Improved it via#https://github.com/VahidN/DNTCaptcha.Core/commit/8721124b8005fbb3cf95a7676d7cc167b6bc0905
