### ISSUE TITLE
What about Persian text

### ISSUE THREAD

**Issue by arashkey** [VahidN/DNTCaptcha.Core#117]
I want to write in Persian letters when it shows captcha. Because it becomes much harder to learn Persian letters with a machine learning 
Example of using this link
https://github.com/mojtabamoradi/PersianNumber
how can I do this?

**Comment by VahidN** [comment]
Just set `asp-captcha-generator-language="Persian"` and `asp-captcha-generator-display-mode="NumberToWord"` options.
