### ISSUE TITLE
Refresh button

### ISSUE THREAD

**Issue by hbatuhankurt** [VahidN/DNTCaptcha.Core#118]
# Summary of the issue

The image of the refresh button is not visible.

## Environment

```
DNTCaptcha.Core version: 
.NET Core SDK version: 
IDE: 
```

## Example code/Steps to reproduce:

```
paste your core code
```

## Output:

```
Exception message:
Full Stack trace:
```

**Comment by VahidN** [comment]
`asp-refresh-button-class="glyphicon glyphicon-refresh btn-sm"` or `asp-refresh-button-class="fas fa-redo btn-sm"` uses a web icon font, such as [this one](https://github.com/VahidN/DNTCaptcha.Core/tree/e167d5bc241aeaf9af78892140fd51ffb84e309b/src/DNTCaptcha.TestRazorPages/wwwroot/fonts).
