### ISSUE TITLE
How to use with json custom action input

### ISSUE THREAD

**Issue by tabakhian** [VahidN/DNTCaptcha.Core#119]
Hi dear Vahid, thank you for all of the effort that you put into this library, I used DNTCaptcha a year ago when it was version 3.
Today I tried to update to last version but I noticed that you have changed the way HasRequestValidCaptchaEntry works, it no longer accept custom input model and forces you to send data in from request, in my scenario I need to get those 3 parameters from user by my custom name ViewModel and validate the captcha by passing the model to the validator, am I missing something in document ? can you please help me ?

**Comment by VahidN** [comment]
You can set your custom property `names` [here](https://github.com/VahidN/DNTCaptcha.Core/blob/8721124b8005fbb3cf95a7676d7cc167b6bc0905/src/DNTCaptcha.TestApiApp/Startup.cs#L44).

**Comment by tabakhian** [comment]
DNTCaptcha expects `captcha_text`, `captcha_user_input_text` & `captcha_token` fields to be present in the posted `form` data. Also don't post it as a JSON data. Its `Content-Type` should be `application/x-www-form-urlencoded`.'

Cant I use json input ?
