### ISSUE TITLE
Captcha Angular

### ISSUE THREAD

**Issue by daliri72** [VahidN/DNTCaptcha.Core#12]
Is possible this captcha  implemented on Angular ?

**Comment by VahidN** [comment]
No. This lib uses MVC's routing system, not the client side's routing system.

**Comment by VahidN** [comment]
Take a look at this sample [DNTCaptcha.AngularClient](https://github.com/VahidN/DNTCaptcha.Core/tree/master/src/DNTCaptcha.AngularClient).
