### ISSUE TITLE
FontAwesome 5 button produces not clickable large button

### ISSUE THREAD

**Issue by kobruleht** [VahidN/DNTCaptcha.Core#120]
# Summary of the issue

Using FontAwesome 5 vector refresh button with Bootstrap 5 produces not clickable and very large button

## Environment

.NET 5
ASP.NET MVC
Bootstrap 5
FontAwesome 5

```
DNTCaptcha.Core version: 

4.4.1

.NET Core SDK version: 

.NET 5 latest 

IDE: 

Visual Studio 2019
```

## Example code/Steps to reproduce:

```
            <dnt-captcha asp-captcha-generator-max="99"
                         asp-captcha-generator-min="1"
                         asp-captcha-generator-language="English"
                         asp-captcha-generator-display-mode="ShowDigits"
                         asp-use-relative-urls="false"
                         asp-placeholder="Sisesta number"
                         asp-validation-error-message="Palun sisesta number."
                         asp-font-name="Tahoma"
                         asp-font-size="60"
                         asp-fore-color="#333333"
                         asp-back-color="#ccc"
                         asp-text-box-class="text-box single-line form-control col-md-5"
                         asp-text-box-template="<div class='input-group col-md-5'>{0}</div>"
                         asp-validation-message-class="text-danger"
                         asp-refresh-button-class="fas fa-sync btn-sm"
                         asp-use-noise="true"
                         asp-dir="ltr" />
```

## Output:

![image](https://user-images.githubusercontent.com/1274923/141066221-5b294afd-d064-4c63-9e6c-17315f2b9380.png)

Image is not clickable and too large.

**Comment by VahidN** [comment]
This is not related to this library.
Start reading its documentation such as https://fontawesome.com/v5.15/how-to-use/on-the-web/styling/sizing-icons

**Comment by kobruleht** [comment]
Thank you.
I tried

asp-refresh-button-class="fas fa-sync fa-3x"

In this case button size is normal.

However, click in button is still igored.
FontAwesome javascript replaces button with svg  element. Its click handler is not captured.

Should I create new issue ?

**Comment by VahidN** [comment]
`FontAwesome` uses css to do that. If the click is not working it means you didn't add the required [unobtrusive Ajax library](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.TestWebApp/bundleconfig.json#L21). It's mentioned in the [readme file](https://github.com/VahidN/DNTCaptcha.Core/blob/master/README.md).

**Comment by kobruleht** [comment]
Thank you.
If 
                         asp-refresh-button-class="btn btn-primary  btn-lg"

is used, click refreshes the image.

Also in Bootstrap 3

asp-refresh-button-class="glyphicon glyphicon-refresh btn"

Worked.

Page contains:

<html>
<body>

<link rel="stylesheet" href="/lib/font-awesome/css/all.css" />
<link rel="stylesheet" href="/lib/twitter-bootstrap/css/bootstrap.css" />
<link rel="stylesheet" href="/lib/jqueryui/jquery-ui.css" />
<link rel="stylesheet" href="/css/jquery.ui.menubar.css" />
<script src="/lib/jquery/jquery.js"></script>
 <script src="/lib/twitter-bootstrap/js/bootstrap.bundle.js"></script>
 <script src="/lib/jqueryui/jquery-ui.js"></script>
 <script src="/lib/font-awesome/js/all.js"></script>
 <script src="/lib/jquery-validate/jquery.validate.js"></script>
 <script src="/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
 <script src="/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.js"></script>
<br class="Apple-interchange-newline">
</body>
</html>

So required libraries are added.

**Comment by kobruleht** [comment]
Can you re-open this issue.

**Comment by VahidN** [comment]
- Do you see any errors in the developers console of your browser? (Press F12 and then reload the app)
- There are other options too. You can use the new [bootstrap icons](https://icons.getbootstrap.com/) as well. It has an MIT license.

**Comment by kobruleht** [comment]
There are no errors in console.
Public testcase is at 

https://o.sta.ee/Account/Register

You can examine it.
Application uses FontAwesome icons  widely. I dont want to add bootstrap icons to application only for captcha.

**Comment by VahidN** [comment]
The way you are using this icon, is not compatible with this library. It comments the produced link and replaces it with an object.
