### ISSUE TITLE
NET 6 , non-windows enviroment

### ISSUE THREAD

**Issue by dzambo2302** [VahidN/DNTCaptcha.Core#122]
# Summary of the issue
Since NET 6 Microsoft dropped support of libgdiplus on linux-based platforms, which means System.Drawing.Common only supported on Windows. That means your amazing captcha is able to run only on Windows. Are there any plans to drop System.Drawing.Common and implement one of Microsoft recommended (ImageSharp, SkiaSharp, Microsoft.Maui.Graphics) ?

Thank you.

Microsoft statement from docs:
[Docs](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only)

## Environment
Every non-windows

```
DNTCaptcha.Core version:  every
.NET Core SDK version: NET 6
```

**Comment by VahidN** [comment]
They [don't support](https://github.com/SixLabors/ImageSharp.Drawing/issues/17) right-to-left languages.

**Comment by VahidN** [comment]
Try V4.3.0 with this [NuGet.config](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.Core/NuGet.config) file.

**Comment by dzambo2302** [comment]
Vahid you are the best, it works perfectly!
Thank you!
