### ISSUE TITLE
خطا در شناسایی Captcha ("لطفا کد امنیتی را به رقم وارد نمائید")

### ISSUE THREAD

**Issue by AllahyarJahangir** [VahidN/DNTCaptcha.Core#123]
سلام
من از captcha در قسمت لاگین استفاده کردم
بعد از پر کردن عبارت نمایش داده شده در Captcha و زدن کلید login پیغام "لطفا کد امنیتی را به رقم وارد نمائید" نمایش داده می شود.
لازم به ذکر است که این مشکل تنها در مرورگر Chrome اتفاق می افتد و در مرورگر Firefox بدون مشکل login می شود. (این مشکل را روی چندین سیستم تست کردم و تمامی سیستم ها به همین شکل می باشد)

**Comment by VahidN** [comment]
سلام؛ آزمايش‌هاي من با كروم هست عموما و مشكلي مشاهده نشد
بهتر است دكمه‌ي f12 را فشار دهيد و در developer console مشاهده كنيد كه آيا خطايي هست؟
همچنين [سطح لاگ سيستم](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.TestWebApp/appsettings.json#L3) را هم مي‌شود به ديباگ تنظيم كرد تا اگر سمت سرور اطلاعات بيشتري وجود دارد، بتوان مشاهده كرد
