### ISSUE TITLE
Upgrade to 4.3.0 failis due to missing SixLabors.ImageSharp.Drawing package

### ISSUE THREAD

**Issue by kobruleht** [VahidN/DNTCaptcha.Core#124]
# Summary of the issue

Trying to upgrade from 4.2.0 to 4.3.0 in .NET 6 using NuGet fails with error

NU1102	Unable to find package SixLabors.ImageSharp.Drawing with version (>= 1.0.0-beta13.15)
  - Found 13 version(s) in nuget.org [ Nearest version: 1.0.0-beta13 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages

## Environment

Visual Studio 2022
.NET 6 MVC application project
```
DNTCaptcha.Core version: 

4.2.0 

.NET Core SDK version: 

.NET 6

IDE: 

Visual Studio 2022

**Comment by VahidN** [comment]
Yes. It's mentioned at the end of the readme file.

> 
You will need this [NuGet.config](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.Core/NuGet.config) file to restore the required dependencies.

**Comment by rbsdotnet** [comment]
برای رفع این مورد چه اقدامی لازم هست؟

**Comment by VahidN** [comment]
Copy [this file](https://raw.githubusercontent.com/VahidN/DNTCaptcha.Core/master/src/DNTCaptcha.Core/NuGet.config) to the root dir of your project.

**Comment by hedyehloo** [comment]
> Copy [this file](https://raw.githubusercontent.com/VahidN/DNTCaptcha.Core/master/src/DNTCaptcha.Core/NuGet.config) to the root dir of your project.

thanks Vahid,
worked by deleting the "www" phrase. 
`https://myget.org/F/sixlabors/api/v3/index.json`
