### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by hedyehloo** [VahidN/DNTCaptcha.Core#127]
# Summary of the issue
Hi,
I got an error with  SixLabors.ImageSharp.Drawing package.

## Environment

```
DNTCaptcha.Core version:  4.3.1
.NET Core SDK version: 6.0.101
IDE:  VS 2022



Exception message:
Full Stack trace:
```
NU1102: Unable to find package SixLabors.ImageSharp.Drawing with version (>= 1.0.0-beta13.15)
  - Found 13 version(s) in nuget.org [ Nearest version: 1.0.0-beta13 ]

**Comment by VahidN** [comment]
https://github.com/VahidN/DNTCaptcha.Core/issues/124#issuecomment-997198154
