### ISSUE TITLE
Is there a way to handle these unhandled exceptions in the DNTCaptchaImage Controller?

### ISSUE THREAD

**Issue by mgh9** [VahidN/DNTCaptcha.Core#131]
Is there a way to handle all unhandled exceptions thrown from the Captcha component?

## Environment

```
DNTCaptcha.Core version: 4.1.1
.NET Core SDK version: 5.0
IDE: Visual Studio 2019 (and IIS 10 in a published envrionment)
```

## Example code/Steps to reproduce:
Just enter any invalid string in the `data` parameter of the `DNTCaptchaImageController.Show` in the URL.

e.g:
```
https://some-website/DNTCaptchaImage/Show?data=--1%27%20or%201=1
https://some-website/DNTCaptchaImage/Show?data=abcd
```

## Output:
See the attached image below :
![dnt-captcha unhandled exceptions issue](https://user-images.githubusercontent.com/56910329/153755668-ddb0ff24-67ad-4825-bfba-5713f3f8c5f7.png)

**Comment by VahidN** [comment]
No. This is how it works. Don't like it? Don't use it.
