### ISSUE TITLE
Captcha Image is not displayed as the older version.

### ISSUE THREAD

**Issue by saineshwar** [VahidN/DNTCaptcha.Core#133]
# Captcha Image is not displayed as the older version and Noise is also not showing properly.

**New Version**

![image](https://user-images.githubusercontent.com/8281689/160139131-e38b93e9-17ea-4795-9f76-b066dafd893d.png)

**Old Version**

![image](https://user-images.githubusercontent.com/8281689/160225232-e60c9e22-5f57-452c-823f-5a496c319900.png)

## Environment 

```
DNTCaptcha.Core version: 4.3.3
.NET Core SDK version: .Net 5.0
IDE: VS 2019
```

## Example code/Steps to reproduce:

```
View Code
----------------
<dnt-captcha asp-captcha-generator-max="999999"
                                     asp-captcha-generator-min="111111"
                                     asp-captcha-generator-language="English"
                                     asp-captcha-generator-display-mode="ShowDigits"
                                     asp-use-relative-urls="true"
                                     asp-placeholder="Enter Security code"
                                     asp-validation-error-message="Please enter the security code."
                                     asp-font-name="Tahoma"
                                     asp-font-size="20"
                                     asp-fore-color="#333333"
                                     asp-back-color="#FCF6F5FF"
                                     asp-text-box-class="text-box form-control"
                                     asp-text-box-template="<span class='input-group-prepend'><span class='form-group-text'></span></span>{0}"
                                     asp-validation-message-class="text-danger"
                                     asp-refresh-button-class="fas fa-redo btn-sm"
                                     asp-dir="ltr"
                                     asp-use-noise="true" />


Startup Code
----------------

 services.AddDNTCaptcha(options =>

                options.UseCookieStorageProvider()
                    .ShowThousandsSeparators(false)
                    .WithEncryptionKey("9F3baE2KFTM7m0C^tt%^Ag")
                    .AbsoluteExpiration(minutes: 7)
                    .WithNoise(pixelsDensity: 50, linesCount: 10)
                    

            );

```

## Output:

```
Exception message:
Full Stack trace:
```

**Comment by VahidN** [comment]
Yes. If you are not happy with it, you can change it and [implement your own image provider.](https://github.com/VahidN/DNTCaptcha.Core#how-to-usecreate-a-different-image-provider) or you can use [the old provider](https://github.com/VahidN/DNTCaptcha.Core/blob/06fe28fd856922e7a4bc2f89c9c93d41bdd14689/src/DNTCaptcha.Core/CaptchaImageProvider.cs) as well.

**Comment by saineshwar** [comment]
> Yes. If you are not happy with it, you can change it and [implement your own image provider.](https://github.com/VahidN/DNTCaptcha.Core#how-to-usecreate-a-different-image-provider) or you can use [the old provider](https://github.com/VahidN/DNTCaptcha.Core/blob/06fe28fd856922e7a4bc2f89c9c93d41bdd14689/src/DNTCaptcha.Core/CaptchaImageProvider.cs) as well.

Image is displayed as box need to increase image width which will make it good. 
Sample
![image](https://user-images.githubusercontent.com/8281689/160748962-7191b420-0501-4af7-82b8-4812299b254f.png)
