### ISSUE TITLE
عدم نمایش تصویر روی سرور لینوکس - Couldn't deserialize the model

### ISSUE THREAD

**Issue by parsintalk** [VahidN/DNTCaptcha.Core#134]
# Summary of the issue
ضمن عرض سلام و تشکر ویژه از زحماتتون.
من Captcha شما رو مدت هاست استفاده می کنم.
در حال حاضر یه نسخه از سایتم رو روی ubuntu نصب کردم.
Captcha روی سرور ویندوز به درستی نمایش داده میشه، اما روی سرور لینوکس نمایش نمیده  و خطای 
Couldn't deserialize the model رو دریافت می کنم.
بعد از trace کد، ظاهرا مقادیر ناشی از decrypt و encrypt یکی نیستند.
شما پیشنهادی ندارید؟
با سپاس فراوان

## Environment
ubuntu 20.04

DNTCaptcha.Core version: 4.3.3
.NET Core SDK version: .net 6.0
IDE: vs 2022

**Comment by VahidN** [comment]
[شبيه به اين نمونه است](https://github.com/VahidN/DNTCaptcha.Core/issues/128#issuecomment-1047703105)

**Comment by parsintalk** [comment]
ممنون، مشکل نبودن فونت tahoma روی لینوکس بود که با UseCustomFont، حل شد.
