### ISSUE TITLE
حذف توکن وقتی متن کپچا صحیح وارد نشده

### ISSUE THREAD

**Issue by mrmashal** [VahidN/DNTCaptcha.Core#137]
سلام. به نظر میاد توی این کامیت: 4002d467d35ec7caa9133fa2e3cc0e71ad5dc201 حذف توکن  وقتی `captchaText` صحیح نیست رو فراموش کرده باشید (در `DNTCaptchaValidatorService.ValidateCaptcha`)

اینجا:
https://github.com/VahidN/DNTCaptcha.Core/blob/4002d467d35ec7caa9133fa2e3cc0e71ad5dc201/src/DNTCaptcha.Core/DNTCaptchaValidatorService.cs#L89-L97

**Comment by VahidN** [comment]
[به كار اضافي نيازي نيست.](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.Core/CookieCaptchaStorageProvider.cs#L77)
