### ISSUE TITLE
کپتچا بار اول همیشه خطا میده و درست تشخیص داده نمیشه ولی بار دوم درست کار میکنه . چرا ؟

### ISSUE THREAD

**Issue by soheilpmr** [VahidN/DNTCaptcha.Core#138]
# Summary of the issue

## Environment

```
DNTCaptcha.Core version: 
.NET Core SDK version: 
IDE: 
```

## Example code/Steps to reproduce:

```
paste your core code
```

## Output:

```
Exception message:
Full Stack trace:
```

**Comment by VahidN** [comment]
خطايي ارسال نكردي؟

**Comment by soheilpmr** [comment]
![2](https://user-images.githubusercontent.com/54750493/176616799-545ad817-2dd0-409d-9708-1c0ed186f4a4.JPG)

**Comment by VahidN** [comment]
شايد بهتر باشد [حالت‌هاي ذخيره سازي متفاوتي](https://github.com/VahidN/DNTCaptcha.Core#how-to-choose-a-correct-storage-mode) را آزمايش كنيد.

**Comment by VahidN** [comment]
بله. حالت‌هاي ديگر را هم آزمايش كنيد.
