### ISSUE TITLE
 disposable captcha

### ISSUE THREAD

**Issue by elahekhanis** [VahidN/DNTCaptcha.Core#140]
# Summary of the issue
Can create a disposable captcha? 
I need create a captcha for one use only . 

## Environment

```
DNTCaptcha.Core version: 
.NET Core SDK version: 
IDE: 
```

## Example code/Steps to reproduce:

```
paste your core code
```

## Output:

```
Exception message:
Full Stack trace:
```

**Comment by VahidN** [comment]
It's disposable. you can't use its generated info for the 2nd time.
