### ISSUE TITLE
DNTCapcha.core not working on server

### ISSUE THREAD

**Issue by sarayutpud** [VahidN/DNTCaptcha.Core#141]
# Summary of the issue
DNTCapcha.core can run normal is debug mode but away varidate fail when public  help me please

## Environment
Iis server
```
DNTCaptcha.Core version: 4.3.3.0
.NET Core SDK version: 6.0
IDE: visual studio 
```

## Example code/Steps to reproduce:
[ValidateDNTCaptcha(ErrorMessage = "กรุณาระบุผลรวมของตัวเลขให้ถูกต้อง",
                    CaptchaGeneratorLanguage = Language.English,
                    CaptchaGeneratorDisplayMode = DisplayMode.ShowDigits)]
<div class="fv-row mb-10 form-group text-center">
                        <dnt-captcha asp-captcha-generator-max="30"
                                 asp-captcha-generator-min="1"
                                 asp-captcha-generator-language="English"
                                 asp-captcha-generator-display-mode="ShowDigits"
                                 asp-use-relative-urls="true"
                                 asp-placeholder="กรุณาระบุตัวเลขตามรูปด้านบน"
                                 asp-validation-error-message="กรุณาระบุตัวเลขให้ถูกต้อง"
                                 asp-font-name="Tahoma"
                                 asp-font-size="20"
                                 asp-fore-color="#333333"
                                 asp-back-color="#FCF6F5FF"
                                 asp-text-box-class="form-control"
                                 asp-text-box-template="<div class='input-group'><span class='input-group-text'><span class='bi-lock'></span></span>{0}</div>"
                                 asp-validation-message-class="text-danger"
                                 asp-refresh-button-class="bi-arrow-counterclockwise btn-lg"
                                 asp-show-refresh-button="true"
                                 asp-dir="ltr" />
                    </div>

```
paste your core code
```

## Output:

```
Exception message:
Full Stack trace:
```

**Comment by sarayutpud** [comment]
i miss some config

**Comment by terryvargas98** [comment]
what was the solution ? i have the same problem

**Comment by VahidN** [comment]
[Follow this thread to know how to debug it.](https://github.com/VahidN/DNTCaptcha.Core/issues/143)
