### ISSUE TITLE
capcha not loading in many request

### ISSUE THREAD

**Issue by sarayutpud** [VahidN/DNTCaptcha.Core#142]
# Summary of the issue

capcha not loading in many request

## Environment
windows server 2019
```
DNTCaptcha.Core version: 4.3.3
.NET Core SDK version: 6.07
IDE: visual studio 2019
```

## Example code/Steps to reproduce:

builder.Services.AddDNTCaptcha(options =>
{
    // options.UseSessionStorageProvider() // -> It doesn't rely on the server or client's times. Also it's the safest one.
    // options.UseMemoryCacheStorageProvider() // -> It relies on the server's times. It's safer than the CookieStorageProvider.
    options.UseCookieStorageProvider(SameSiteMode.Lax) // -> It relies on the server and client's times. It's ideal for scalability, because it doesn't save anything in the server's memory.
                                                          // .UseDistributedCacheStorageProvider() // --> It's ideal for scalability using `services.AddStackExchangeRedisCache()` for instance.
                                                          // .UseDistributedSerializationProvider()

    // Don't set this line (remove it) to use the installed system's fonts (FontName = "Tahoma").
    // Or if you want to use a custom font, make sure that font is present in the wwwroot/fonts folder and also use a good and complete font!
    //.UseCustomFont(Path.Combine(_env.WebRootPath, "fonts", "IRANSans(FaNum)_Bold.ttf")) // This is optional.
    .AbsoluteExpiration(minutes: 9999)
    .ShowThousandsSeparators(false)
    .WithNoise(pixelsDensity: 25, linesCount: 3)
    .WithEncryptionKey("GSBkey!")
    .InputNames(// This is optional. Change it if you don't like the default names.
        new DNTCaptchaComponent
        {
            CaptchaHiddenInputName = "DNTCaptchaTextGSB",
            CaptchaHiddenTokenName = "DNTCaptchaTokengGSB",
            CaptchaInputName = "DNTCaptchaInputTextGSB"
        })
    .Identifier("dntCaptcha")// This is optional. Change it if you don't like its default name.
    ;
});

[ValidateDNTCaptcha(ErrorMessage = "กรุณาระบุตัวเลขให้ถูกต้อง",
                    CaptchaGeneratorLanguage = Language.English,
                    CaptchaGeneratorDisplayMode = DisplayMode.ShowDigits)]
```
paste your core code
```

## Output:

```
Exception message:
Full Stack trace:
```
![Screenshot (1)](https://user-images.githubusercontent.com/8022560/198175742-b42226f5-7d0c-40d5-9f94-1d4f4374921b.png)

![image](https://user-images.githubusercontent.com/8022560/198175329-4512d46f-cf72-4063-9f33-59509d5e7f6a.png)

**Comment by VahidN** [comment]
Yes. You can't fetch the same URL many times. Because its token will be invalidated.
