### ISSUE TITLE
I can not see captcha image in linux containers

### ISSUE THREAD

**Issue by mehmet-erdogdu** [VahidN/DNTCaptcha.Core#143]
# Summary of the issue

I can not see captcha image in linux containers

## Environment

```
DNTCaptcha.Core version: 4.3.3
.NET Core SDK version:  6.0
IDE: 
```

## Example code/Steps to reproduce:

```
paste your core code
```

## Output:
![image](https://user-images.githubusercontent.com/44897996/199241096-884df2dd-0534-4029-9608-ff690610a4f3.png)

Exception message:
Full Stack trace:
```

**Comment by mehmet-erdogdu** [comment]
linux
![image](https://user-images.githubusercontent.com/44897996/199899036-e6194349-b5e4-4b2e-ab98-3b5f80ea0cbb.png)

windows
![image](https://user-images.githubusercontent.com/44897996/199897561-a9a050fb-07ae-4a53-aca7-a2bbb1a42c25.png)

**Comment by VahidN** [comment]
If you want to see the output of [_logger.LogDebug](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.Core/DNTCaptchaImageController.cs#L188), you should [turn on this level of logging](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.TestWebApp/appsettings.json#L3) in the appsettings.json file.

**Comment by mehmet-erdogdu** [comment]
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:49159/DNTCaptchaImage/Show?data=UPSw9DUeJhw7X2_t_1dCI_IfsaBSI76A4Q4tWmJswdVIAMV2kSJkkUcz3hfxDxUK9hw_TsLThGcqh0bAMtgQ9U7vwW2ayazPnw2KNmSFJ-E - -
dbug: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[4]
      The request path /DNTCaptchaImage/Show does not match a supported file type
dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1001]
      1 candidate(s) found for the request path '/DNTCaptchaImage/Show'
dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1005]
      Endpoint 'DNTCaptcha.Core.DNTCaptchaImageController.Show (DNTCaptcha.Core)' with route pattern 'DNTCaptchaImage/Show' is valid for the request path '/DNTCaptchaImage/Show'
dbug: Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware[1]
      Request matched endpoint 'DNTCaptcha.Core.DNTCaptchaImageController.Show (DNTCaptcha.Core)'
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'DNTCaptcha.Core.DNTCaptchaImageController.Show (DNTCaptcha.Core)'
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "Show", controller = "DNTCaptchaImage"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Show(System.String) on controller DNTCaptcha.Core.DNTCaptchaImageController (DNTCaptcha.Core).
dbug: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[1]
      Execution plan of authorization filters (in the following order): None
dbug: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[1]
      Execution plan of resource filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.SaveTempDataFilter
dbug: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[1]
      Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter
dbug: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[1]
      Execution plan of exception filters (in the following order): None
dbug: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[1]
      Execution plan of result filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.SaveTempDataFilter
dbug: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[1]
      Executing controller factory for controller DNTCaptcha.Core.DNTCaptchaImageController (DNTCaptcha.Core)
dbug: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed controller factory for controller DNTCaptcha.Core.DNTCaptchaImageController (DNTCaptcha.Core)
dbug: Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder[22]
      Attempting to bind parameter 'data' of type 'System.String' ...
dbug: Microsoft.AspNetCore.Mvc.ModelBinding.Binders.SimpleTypeModelBinder[44]
      Attempting to bind parameter 'data' of type 'System.String' using the name 'data' in request data ...
dbug: Microsoft.AspNetCore.Mvc.ModelBinding.Binders.SimpleTypeModelBinder[45]
      Done attempting to bind parameter 'data' of type 'System.String'.
dbug: Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder[23]
      Done attempting to bind parameter 'data' of type 'System.String'.
dbug: Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder[26]
      Attempting to validate the bound parameter 'data' of type 'System.String' ...
dbug: Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder[27]
      Done attempting to validate the bound parameter 'data' of type 'System.String'.
dbug: DNTCaptcha.Core.DNTCaptchaImageController[0]
      Failed to show the captcha image.
      SixLabors.Fonts.FontFamilyNotFoundException: The "Tahoma" font family could not be found
         at SixLabors.Fonts.FontCollection.GetImpl(String name, CultureInfo culture)
         at DNTCaptcha.Core.CaptchaImageProvider.getFont(String fontName, Single fontSize) in D:\Prog\1395\DNTCaptcha.Core\src\DNTCaptcha.Core\CaptchaImageProvider.cs:line 106
         at DNTCaptcha.Core.CaptchaImageProvider.DrawCaptcha(String message, String foreColor, String backColor, Single fontSize, String fontName) in D:\Prog\1395\DNTCaptcha.Core\src\DNTCaptcha.Core\CaptchaImageProvider.cs:line 40
         at DNTCaptcha.Core.DNTCaptchaImageController.Show(String data) in D:\Prog\1395\DNTCaptcha.Core\src\DNTCaptcha.Core\DNTCaptchaImageController.cs:line 183
dbug: Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector[11]
      List of registered output formatters, in the following order: Microsoft.AspNetCore.Mvc.Formatters.HttpNoContentOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StringOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StreamOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter
dbug: Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector[4]
      No information found on request to perform content negotiation.
dbug: Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector[8]
      Attempting to select an output formatter without using a content type as no explicit content types were specified for the response.
dbug: Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector[10]
      Attempting to select the first formatter in the output formatters list which can write the result.
dbug: Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector[2]
      Selected output formatter 'Microsoft.AspNetCore.Mvc.Formatters.StringOutputFormatter' and content type 'text/plain' to write the response.
info: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[1]
      Executing BadRequestObjectResult, writing value of type 'System.String'.
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action DNTCaptcha.Core.DNTCaptchaImageController.Show (DNTCaptcha.Core) in 180.2505ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'DNTCaptcha.Core.DNTCaptchaImageController.Show (DNTCaptcha.Core)'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:49159/DNTCaptchaImage/Show?data=UPSw9DUeJhw7X2_t_1dCI_IfsaBSI76A4Q4tWmJswdVIAMV2kSJkkUcz3hfxDxUK9hw_TsLThGcqh0bAMtgQ9U7vwW2ayazPnw2KNmSFJ-E - - - 400 - text/plain;+charset=utf-8 227.5269ms

**Comment by mehmet-erdogdu** [comment]
Failed to show the captcha image.
SixLabors.Fonts.FontFamilyNotFoundException: The "Tahoma" font family could not be found

**Comment by VahidN** [comment]
You can install the Tahoma font in your system or you can [just use a custom font](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.TestWebApp/Startup.cs#L60).

**Comment by mehmet-erdogdu** [comment]
thanks this worked.
![image](https://user-images.githubusercontent.com/44897996/199932112-430405b7-0178-4bf4-a718-c8d113743187.png)

**Comment by VahidN** [comment]
You can use `builder.Environment` for the `IHostEnvironment`.
