### ISSUE TITLE
update to 4.4.0 and problem with api

### ISSUE THREAD

**Issue by nikkhoo63** [VahidN/DNTCaptcha.Core#145]
سلام و خسته نباشید
به نسخه 4.4.0 آپدیت کردم در صفحات عادی که از کپچا استفاده کردم مشکلی نیست ولی در صفحاتی که بصورت api از کپچا استفاده کردم عدم درست بودن کپچا رو به کاربر بر میگردونه.
در نسخه 4.3.3 هیچ مشکلی نداشتم و الان هم که به این نسخه برگردوندم کپچا داره کار می کنه ولی با نسخه جدید مشکل داره
اینم کد کپچا:

```cs
[HttpGet("[action]")]
        [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true, Duration = 0)]
        public ActionResult<DNTCaptchaApiResponse> CreateDNTCaptchaParams(string code = "")
        {
            var captcha = _apiProvider.CreateDNTCaptcha(new DNTCaptchaTagHelperHtmlAttributes
            {
                BackColor = "#f7f3f3",
                ForeColor = "#111111",
                FontSize = 19,
                Language = Language.Persian,
                DisplayMode = DisplayMode.ShowDigits,
                Max = 99999,
                Min = 1001,
                CaptchaToken = "NewCaptchaToken",
            });
            return captcha;
        }
```

**Comment by VahidN** [comment]
- تنها تغييري كه در نسخه 4.4 بوده، تغيير نحوه‌ي نمايش تصوير آن هست و نه هيچ مورد ديگري.
- [اين مثال را هم بررسي كردم مشكلي نبود](https://github.com/VahidN/DNTCaptcha.Core/tree/master/src/DNTCaptcha.TestApiApp).
- چه خطايي در قسمت network ابزارهاي توسعه دهندگان مرورگر دريافت مي‌كنيد؟ چه response اي دارد؟

**Comment by nikkhoo63** [comment]
در قسمت network خطایی ندارد. 
بررسی کامل که کردیم به این نتیجه رسیدیم که 
```
Language = Language.Persian,
DisplayMode = DisplayMode.ShowDigits,
```
باشد دچار خطا می شود و در سایر حالت‌ها به درستی پاسخگو است

**Comment by VahidN** [comment]
Try V 4.4.1

**Comment by nikkhoo63** [comment]
سلام. خیلی ممنون. مشکل حل شد. ولی قبلا اعداد فارسی بود الان فقط اعداد انگلیسی نمایش میده و تنظیم زبان به فارسی تاثیری نداره. البته مشکلی نیست ولی اگر حل بشه بهتره

**Comment by VahidN** [comment]
از يك فونت فارسي كه اعداد را فارسي نمايش مي‌دهد استفاده كنيد؛ مانند https://github.com/rastikerdar/samim-font/releases/tag/v4.0.5
