### ISSUE TITLE
Accept Unused Cookies (4.3.3)

### ISSUE THREAD

**Issue by mcelal33** [VahidN/DNTCaptcha.Core#148]
# Summary of the issue
It creates a new cookie when I refresh the captcha or the page. I refreshed my login page 3 times. I kept the values ​​mentioned below at every turn .But I've never used it and I haven't posted. Then I tried to post requests for values I kept orderly in postman. DNTCaptcha accepted all of them.  

Assume that. If anybody creates cookies over 100 . Than It  stores all of data in somewhere , I might  make bruteforce attach to web site . 

Summary ; Last cookie and token , input etc. must be valid. Last values must override others . Others must be disabled

DNTCaptchaInputText		DNTCaptchaText				DNTCaptchaToken
1482	 	 			hu1w1yg1iV74XZwe2iT_nw		c1K5dB2YAhmTzNLTWSAfXhNXKL2nKgFXZ3imwDXmVILUp4UTH-Au93FmLeY-29bVqupSa2RnEShm9BndHqf39qjZOzAbKzR_
594	 					5KO9WWgV27UwoEiJeFA_-Q		Dmk-f3JuDxWW8AI-YZ5eWHjPssQYw9JH9kldom6RPu2BLBLqMWtV7kwRGKwNO5ADkJgM4yxpmsKsDst17ADsQwR-MZLZXRmc
8561	 				oW1M6t5GmKbtlZ_np9Al4g		jg5o7eiU5rdHWa6AYsvEk_BsqcmAcX_NiYqNaq2zP4jnvYGZLGMj-tULK_uHdX1uak-9FaKy_IYY3ds3QOjK1SWTbUID5AwL
## Environment

```
DNTCaptcha.Core version: 4.3.3
.NET Core SDK version: 3.1
IDE: 
```

## Example code/Steps to reproduce:

```
paste your core code
`Email:xxx
Password:xxx
DNTCaptchaText:hu1w1yg1iV74XZwe2iT_nw
DNTCaptchaInputText:1482
DNTCaptchaToken:c1K5dB2YAhmTzNLTWSAfXhNXKL2nKgFXZ3imwDXmVILUp4UTH-Au93FmLeY-29bVqupSa2RnEShm9BndHqf39qjZOzAbKzR_
__RequestVerificationToken:3fdDdJ8Huxvqm-6JhHvXDrL2_1C60CxRmrlDiA5aEYdddYDdfsfwBonxBhiW3UEXfplsznXqLAj6aPdmWLXo8M91nFOaDfD3D_7wQkFhSIspmL7wpOQsqthKY8g59Re_55bcX0wc8RvxzeTa0PVGWV0SIcCCnHuRFfTZh4Jwtix8jSzLMhFtC-dfsafsfds`

## Output:

```
Exception message:
Full Stack trace:
```

**Comment by VahidN** [comment]
It really doesn't matter. Because its token will be invalidated on the first use. It will be marked to be deleted by the browser and I'm not going to track all of the issued cookies by an in-memory cache. It will defeat the purpose of using cookies.
If you don't like cookies, [use other available storages such as cache or session](https://github.com/VahidN/DNTCaptcha.Core#how-to-choose-a-correct-storage-mode).

> Last values must override others.
No. This captcha is designed to support having multi instances of it. This is how it works.

**Comment by mcelal33** [comment]
Thank you. What I try to tell is not using cookie . If you refresh new capcha button or whole page , It generates constantly cookies with different name . Why aren't previous cookie is not deleted when refreshing . I think, last cookie I get must be valid. Previous unused cookies are valid too.
