### ISSUE TITLE
refresh button not working

### ISSUE THREAD

**Issue by Alirezanet** [VahidN/DNTCaptcha.Core#15]
everything is perfect but captcha refresh button not working.

**Comment by VahidN** [comment]
- This library uses unobtrusive Ajax library for the refresh button. Make sure you have included its related scripts too:
  *  [bower.json](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.TestWebApp/bower.json#L9)
  *  [bundleconfig.json](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.TestWebApp/bundleconfig.json#L15)
  * Or include it form a CDN (It requires jQuery 1.4.4+):
  ```javascript
  <script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/mvc/3.0/jquery.unobtrusive-ajax.min.js"></script>
  ```

**Comment by Alirezanet** [comment]
thanks for reply. 
I`m already using this library for validate my forms. so it is included on my page. also its working for dtncaptcha validation errors too. just refresh button not working. 
![11](https://user-images.githubusercontent.com/7004080/35670060-79f430ce-074c-11e8-8e6b-08fa1690a7e6.PNG)

**Comment by VahidN** [comment]
- `jquery.unobtrusive-ajax` is different than `jquery-validation-unobtrusive` which is used for validations.
- What do you see in the developers console's network tab of your browser? are there any errors at there?

**Comment by Alirezanet** [comment]
good point!  i'm not using `jquery.unobtrusive-ajax` and there is no error in browser console.
i added  `jquery.unobtrusive-ajax` i have some errors now. 

`Uncaught TypeError: a(...).live is not a function
    at ajax.aspnetcdn.com/ajax/mvc/3.0/jquery.unobtrusive-ajax.min.js:5
    at ajax.aspnetcdn.com/ajax/mvc/3.0/jquery.unobtrusive-ajax.min.js:5`

**Comment by VahidN** [comment]
Don't use it from the CDN. It seems the CDN version uses deprecated jQuery methods. Try this one: 
https://github.com/aspnet/jquery-ajax-unobtrusive/tree/master/dist
