### ISSUE TITLE
SumOfTwoNumbersToWordsProvider always uses the same second component of sum generated in constructor

### ISSUE THREAD

**Issue by pasviridov** [VahidN/DNTCaptcha.Core#151]
# Summary of the issue

SumOfTwoNumbersToWordsProvider generates the second second component of sum in constructor. Thereby it's the same until we relaunch the application. I'm sure it is right to generate the number in GetText method every time when it is being called.

**Comment by VahidN** [comment]
No. During validation, [this line will be called again](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.Core/DNTCaptchaValidatorService.cs#L92) and in this case the result won't match the last generated text.

**Comment by pasviridov** [comment]
Isn't it more correct to store the number itself in hidden input & storage provider? Then this problem would be gone. I have made the corresponding changes [in my fork](https://github.com/Tesitarium/DNTCaptcha.Core) of your repository and everything works fine. It's up to you, take these updates or not.

**Comment by VahidN** [comment]
Try the new version.
