### ISSUE TITLE
Ubuntu

### ISSUE THREAD

**Issue by mina1917** [VahidN/DNTCaptcha.Core#152]
# Summary of the issue
In Ubuntu Linux Captcha not displaying image 
I Did " Linux (and containers) support" this too.

net Core 6
ubuntu 22.04
DNTCaptcha.Core 4.3.3
![image](https://github.com/VahidN/DNTCaptcha.Core/assets/15322304/655e7b03-819b-4c98-a313-4050e4794dd2)

**Comment by VahidN** [comment]
You should checkout the server's logs and at least you should see what's the response of the requested image. Open the network's tab of the browser's developer tools and see the responses.
If you want to see the output of [_logger.LogDebug](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.Core/DNTCaptchaImageController.cs#L188), you should [turn on this level of logging](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.TestWebApp/appsettings.json#L3) in the appsettings.json file.

**Comment by mina1917** [comment]
"GET /DNTCaptchaImage/Show?data=Lq3czSmPZ4-ohUzc_YK2e61LhT3DNUM1gPIaQo1mN_qo6chFrNMUkntpxoaQDfs1eYkg1FidTeKByuqmL87OGw HTTP/1.1" 400 Bad Request

**Comment by VahidN** [comment]
> Error is : Couldn't deserialize the model.

This means something is cutting/changing some parts of the query string and on the server, this corrupted data can't be decrypted properly. Do you have any filter here such as `LowercaseQueryStrings = true`?

**Comment by VahidN** [comment]
The last version is not using the `SixLabors` anymore. It's `SkiaSharp`.

**Comment by mina1917** [comment]
I use this version Include="DNTCaptcha.Core" Version="4.3.3"
you mean if I use the last version, it will be fixed?
