### ISSUE TITLE
امکان استفاده در دیگر SPA ها

### ISSUE THREAD

**Issue by mirshekarm** [VahidN/DNTCaptcha.Core#153]
با سلام امکانش هست پیاده سازی HTML CSS JS Pure رو ارائه بدید که بشه جاهای مختلفی استفاده کرد؟

مثلا من الان یک پروژه ASP.NET Core Web API دارم و یک پروژه فرانت Vue js ولی نمیدونم چطوری از کپچای شما استفاده کنم.

ممنونم.

**Comment by VahidN** [comment]
[يك نمونه با jQuery اينجا هست براي ايده گرفتن.](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.TestApiApp/wwwroot/index.html)
