### ISSUE TITLE
Captcha not showing when deplyong the system on server

### ISSUE THREAD

**Issue by ManukyanHayk** [VahidN/DNTCaptcha.Core#156]
# Summary of the issue
The captcha is working fine on development environment, however when deploying on the server the captcha image is not showing, The refresh icon showing fine. The server is Windows Server 2022

## Environment

```
DNTCaptcha.Core version: 4.7.0
.NET Core SDK version: .NET 7
IDE: Visual Studio
```

## Example code/Steps to reproduce:
builder.Services.AddDNTCaptcha(options =>
{
    options.UseCookieStorageProvider()
    .AbsoluteExpiration(minutes: 7)
    .ShowThousandsSeparators(false)
    .WithNoise(0.155f, 0.155f, 1, 0.0f)
    .WithEncryptionKey("mykey");
});

<dnt-captcha asp-captcha-generator-max="99999"
             asp-captcha-generator-min="10000"
             asp-captcha-generator-language="English"
             asp-captcha-generator-display-mode="ShowDigits"
             asp-use-relative-urls="true"
             asp-placeholder="Security code as a number"
             asp-validation-error-message="Please enter the security code as a number."
             asp-font-size="30"
             asp-fore-color="#333333"
             asp-back-color="#7865f4"
             asp-text-box-class="text-box form-control"
             asp-text-box-template="<div class='input-group'><span class='input-group-prepend'><span class='input-group-text'><i class='fas fa-lock'></i></span></span>{0}</div>"
             asp-validation-message-class="text-danger"
                 asp-refresh-button-class="fas fa-redo btn-sm refreshCaptchaColor"
             asp-show-refresh-button="true" />

## Output:

```
Exception message:
Full Stack trace:
```
Failed to load resource: the server responded with a status of 400 ()

**Comment by ManukyanHayk** [comment]
Thanks @VahidN for the link. I enabled the log as it was described, please find attached the log that I am receiving. In log file I do not see why the captcha is not being shown? Can I use any text as an encryption key or I should register it somewhere before using it?
You can use the following link to see the captcha on my site that is not being shown.
https://eco.tesnum.am/landing?=%2F#demoSection
[captchaLog.txt](https://github.com/VahidN/DNTCaptcha.Core/files/11889714/captchaLog.txt)
[captchaLog.txt](https://github.com/VahidN/DNTCaptcha.Core/files/11889717/captchaLog.txt)

builder.Services.AddDNTCaptcha(options =>
{
    options.UseCookieStorageProvider(SameSiteMode.None)
    .AbsoluteExpiration(minutes: 7)
    .ShowThousandsSeparators(false)
    .WithNoise(0.155f, 0.155f, 1, 0.0f)
    .WithEncryptionKey("mykey");
});

**Comment by VahidN** [comment]
Use this one for your blazor based app: [DNTCaptcha.Blazor](https://github.com/VahidN/DNTCaptcha.Blazor)

**Comment by ManukyanHayk** [comment]
That page is a .cshtml page not a .razor page, so I think I can not directly use Blazor component in it. My main issue is the captcha is working perfect on developer computer but not working when I deploy it on server.

**Comment by VahidN** [comment]
It shows `Couldn't deserialize the model.` in the response tab which means something is destroying the captcha's data. Probably there's a filter on the page to change elements (such as [LowercaseQueryStrings = true](https://github.com/VahidN/DNTCaptcha.Core#note)) or there's a firewall on the server. Sorry I can't help you with this.
