### ISSUE TITLE
i have used https://docs.sixlabors.com/

### ISSUE THREAD

**Issue by smsrezaei** [VahidN/DNTCaptcha.Core#158]
# Summary of the issue

    <PackageReference Include="SixLabors.Fonts" Version="1.0.0-beta19" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.0.1" />
    <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="1.0.0-beta15" />

        private byte[] createCaptcha(int width , int height, string captchaCode) {
            using (var img = new Image<Rgba32>(width, height))
            {
                var fontFamilies = new string[] { "Arial" };
                Random random = new Random(); img.Mutate(ctx => ctx.BackgroundColor(Color.White));
                float x = 0, y = 0, position = 0;
                img.Mutate(ctx => ctx.DrawLines(Color.Gray, 10, new PointF[] { new PointF(0, 0), new PointF(width, height) }));
                img.Mutate(ctx => ctx.DrawLines(Color.Gray, 5, new PointF[] { new PointF(0, 0), new PointF(width, height) }));
                foreach (char c in captchaCode)
                {
                    var font = SystemFonts.CreateFont(fontFamilies[random.Next(0, fontFamilies.Length)], 20, FontStyle.Regular);
                    var location = new PointF(x + position, y);
                    img.Mutate(ctx => ctx.DrawText(c.ToString(), font, new Color(new Argb32(0.0f, 0.0f, 1.0f)), location));
                    position = position + 20;
                }
                var data = new MemoryStream();
                img.SaveAsPng(data);
                return data.ToArray();
            }
        }

and also arial custom font 

## Environment

```
DNTCaptcha.Core version: 
.NET Core SDK version: 
IDE: 
```

## Example code/Steps to reproduce:

```
paste your core code
```

## Output:

```
Exception message:
Full Stack trace:
```

**Comment by smsrezaei** [comment]
recommended by microsoft

**Comment by smsrezaei** [comment]
https://medium.com/agile-content-teamwork/captcha-generator-with-sixlabors-libs-on-net-core-3-c0d2600b01d5

**Comment by smsrezaei** [comment]
Recommended action

To use these APIs for cross-platform apps, migrate to one of the following libraries:

    [ImageSharp](https://sixlabors.com/products/imagesharp)
    **[SkiaSharp](https://github.com/mono/SkiaSharp)**
    [Microsoft.Maui.Graphics](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/graphics/)

**Comment by VahidN** [comment]
Stop spamming here. It's already done.
