### ISSUE TITLE
رد تست امنیت از سوی بانک

### ISSUE THREAD

**Issue by KAJOOSH** [VahidN/DNTCaptcha.Core#159]
سلام

احتراما طی ارزیابی آخرین نگارش موجود فریم ورک توسط یکی از بانک های داخلی نتیجه به شرح ذیل می باشد

![image](https://github.com/VahidN/DNTCaptcha.Core/assets/47478490/d2dd725b-f8da-42df-a6f6-42f71cfdacd5)

**Comment by VahidN** [comment]
از حالت كوكي استفاده نكنيد.
