### ISSUE TITLE
csp راهکار حل

### ISSUE THREAD

**Issue by KAJOOSH** [VahidN/DNTCaptcha.Core#160]
سلام
در صورت فعال سازی csp با خطا رو به رو میشویم. طی جستجو قبلا در #54 و #132 مطرح شده است اما راهکاری ارائه نشده است.
امکان فعال سازی "unsafe-inline" وجود ندارد و اسکریپت نیز هر دفعه هش کد جدید تولید می کند ( چرا که هر دفعه توکن جدید ایجاد می شود) و نمی توان مقدار هش کد ثابت آن ثبت نمود.
لطفا در صورت ممکن راهکاری در این زمینه ارائه دهید.

* [برای امن سازی این موضوع از این روش استفاده کرده ایم](https://www.dntips.ir/post/3483/%d8%a8%d9%87%d8%a8%d9%88%d8%af-%d8%a7%d9%85%d9%86%db%8c%d8%aa-csp-%d8%a8%d8%a7-%d8%a7%d8%b3%d8%aa%d9%81%d8%a7%d8%af%d9%87-%d8%a7%d8%b2-%d9%85%d8%b9%d8%b1%d9%81%db%8c-%d9%87%d8%b4%e2%80%8c%d9%87%d8%a7%db%8c-%d8%a7%d8%b3%da%a9%d8%b1%db%8c%d9%be%d8%aa%e2%80%8c%d9%87%d8%a7%db%8c-inline)

**Comment by KAJOOSH** [comment]
به عنوان راهکار پیشنهادی می توان attributes سفارشی از سمت ما در تگ script ارسال شود به طور مثال:

`<script nonce="ryPzmoZScSR2xOwV0qTU9mFdFwGPN&#x2B;gy3S2E1/VK1vg=">`
بعد در [NetEscapades.AspNetCore.SecurityHeaders](https://github.com/andrewlock/NetEscapades.AspNetCore.SecurityHeaders) می توان مقدار هش را ثبت کرد.

**Comment by VahidN** [comment]
خالي نيست. از گزينه‌ي view source استفاده كنيد.

**Comment by KAJOOSH** [comment]
درست می فرمایید :-) 
اما هر دفعه یه هش کد میده که باعث میشه وقتی رفرش می کنیم خطای های زیر داده بشود:
![error5](https://github.com/VahidN/DNTCaptcha.Core/assets/47478490/6679b6ce-0346-449d-ae5b-8b5372ba4aa6)
برای StyleSrc هم راهکاری دارید؟!

**Comment by VahidN** [comment]
اين‌ها ارتباطي به كتابخانه‌ي جاري ندارند. زمانيكه از hot reload و يا افزونه‌ي خاصي استفاده مي‌شود، يكسري اسكريپت و استايل را به صورت خودكار به صفحه تزريق مي‌كنند.

**Comment by KAJOOSH** [comment]
به این دو تصویر نگاه کنید. هر دفعه هش کد جدید تولید می شود زمان رفرش کپچا.
به نظر شما درست است ؟!
![error6](https://github.com/VahidN/DNTCaptcha.Core/assets/47478490/4bfe5195-73ca-4e9a-9625-90bfabcea7f8)
![error7](https://github.com/VahidN/DNTCaptcha.Core/assets/47478490/88bcd8f3-02df-41b1-b906-14283e9e3b46)

**Comment by VahidN** [comment]
[بله. اينجا توضيح دادم.](https://www.dntips.ir/post/3483/%d8%a8%d9%87%d8%a8%d9%88%d8%af-%d8%a7%d9%85%d9%86%db%8c%d8%aa-csp-%d8%a8%d8%a7-%d8%a7%d8%b3%d8%aa%d9%81%d8%a7%d8%af%d9%87-%d8%a7%d8%b2-%d9%85%d8%b9%d8%b1%d9%81%db%8c-%d9%87%d8%b4%e2%80%8c%d9%87%d8%a7%db%8c-%d8%a7%d8%b3%da%a9%d8%b1%db%8c%d9%be%d8%aa%e2%80%8c%d9%87%d8%a7%db%8c-inline#comment-19290)
