### ISSUE TITLE
Set Number for Textbox

### ISSUE THREAD

**Issue by j-ghadiri** [VahidN/DNTCaptcha.Core#167]
Hi @VahidN 

It is very useful if it converts the Persian numerical characters into Latin numbers when checking the numbers on the server side.

for example use this method :

```c#
public static string Fa2En(this string str)
        {
            return str.Replace("۰", "0")
                .Replace("۱", "1")
                .Replace("۲", "2")
                .Replace("۳", "3")
                .Replace("۴", "4")
                .Replace("۵", "5")
                .Replace("۶", "6")
                .Replace("۷", "7")
                .Replace("۸", "8")
                .Replace("۹", "9")
                //iphone numeric
                .Replace("٠", "0")
                .Replace("١", "1")
                .Replace("٢", "2")
                .Replace("٣", "3")
                .Replace("٤", "4")
                .Replace("٥", "5")
                .Replace("٦", "6")
                .Replace("٧", "7")
                .Replace("٨", "8")
                .Replace("٩", "9");
        }
``` 

 
Or :
How to set this textbox type to "Tel" to prevent the entry of numerical characters in the form of Persian numbers?

[https://github.com/VahidN/DNTCaptcha.Core/blob/9c18c50297a68598bbdc4091c74ff1e1920f9931/src/DNTCaptcha.Core/DNTCaptchaTagHelper.cs#L333](https://github.com/VahidN/DNTCaptcha.Core/blob/9c18c50297a68598bbdc4091c74ff1e1920f9931/src/DNTCaptcha.Core/DNTCaptchaTagHelper.cs#L333)

**Comment by VahidN** [comment]
[It does convert Persian numbers to English numbers during the validation phase.](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.Core/DNTCaptchaValidatorService.cs#L72)
