### ISSUE TITLE
وابسته بودن به httpcontext و نبودن سرویس های جداگانه

### ISSUE THREAD

**Issue by EngRajabi** [VahidN/DNTCaptcha.Core#169]
در حالتی از این lib بخواهیم در محیط میکروسرویس به عنوان as service بدهیم که همه میکرو ها و پروژه ها از این lib استفاده کنن برای تولید کپچا. من متاسفانه این قابلیت رو ندیدم و دیدم کد ها coupled شده بودن به httpcontext
خیلی خوب میشد اگر یک کلاس تهریف میشد که کلا ۲ تا متد داشت. تولید عکس و وریفای عکس. فارغ از http context و mvc و...

**Comment by EngRajabi** [comment]
این مثال رو خواندم. این مثال هم دقیقا وابسته HttpContext هست. یعنی کسی که میخواهد استفاده بکند باید حتما این پکیچ رو روی میکرو سرویس های که نیاز داره نصب بکنه و استفاده بکنه.
نمیتونه یک جا نصب بکنه بقیه ازش استفاده بکنن

**Comment by VahidN** [comment]
- توليد و بررسي كپچا، صرفا كار توليد عكس ساده نيست. يك قسمت آن مديريت حالت هست كه توسط HttpContext صورت مي‌گيرد. بله از HttpContext استفاده مي‌كند چون در محيط بدون حالت وب (stateless)، همينكه بتوان اين دو قسمت (توليد و بررسي اطلاعات دريافتي) را به هم ربط داد، يك هنر است.
- مثال‌هاي جاوااسكريپتي آن خصوصا نمونه‌ي Angular، دقيقا به معناي امكان استفاده‌ي از آن به صورت سرويس هست و  ارسال اطلاعات به سرور بررسي كننده‌ي اعتبار آن از كلاينتي جاوااسكريپتي كه الزاما بر روي دومين توليد كننده‌ي كپچا نيست (توليد كننده‌ي كپچا روي سرور ASP.NET Core هست و برنامه‌ي تمام كلاينتي Angular، كاملا مجزاي از آن و بر روي يك سرور ديگر)، با CORS كار مي‌كند. همچنين امكان ذخيره سازي اطلاعات آن، به صورت توزيع شده هم وجود دارد (قسمت How to choose a correct storage mode در ReadMe).

**Comment by EngRajabi** [comment]
من کد شما رو کامل دیدم.
در این سناریه که کانفیگ به صورت DistributedCacheCaptchaStorageProvider باشد شما عملا از HttpContext برای Salt که اونم از UserAgent هست استفاده میکنید. برای وریفای درخواست کپچا
برای نکته اول شما، این سناریو رو در نظر بگیرید که کلاسی وجود دارد که 2 تا متد دارد. یک متد عکس را تولید میکند و به عنوان خروجی base64 عکس به همراه توکن به خروجی ارسال میکند. متد دومی ورودی کاربر با توکن عکس رو دریافت میکند. اینکار باعث میشه فارغ از اینکه عکس کجا و به چه شکل در حال نمایش است بتوان کار را انجام داد. فرض کنید در بین میکروسرویس هاتون یک میکرو سرویس ایجاد و تایید کپچا رو به کل سازمان و میکرو ها میده. این سرویس میتونه بر پایه grpc یا rest باشه. و دست بقیه باز هست که چطوری نمایش و کار میکنن باهاش.
اما با فلو دیزایش فعلی ما باید Endpoint ورودی کاربر باشیم و نمیتونیم به عنوان as service این امکان رو بدیم. پس مجبوریم این پکیچ رو روی هر پروژه ایی که کپچا نیاز باشه نصب و کانفیگ و نگه داری کنیم.
امیدوارم تونسته باشیم منظورم رو کامل منتقل بکنم
من کد شما رو با DataProtection سمت خودم بازنویسی کردم برای بحث رمزنگاری

**Comment by VahidN** [comment]
- خوب، روش ارائه‌ي اطلاعات اين پروژه به يك كلاينت جاوااسكريپتي بر همين مبناي سرويس Rest هست. حالا چون دقيقا با طراحي توكني مدنظر شما يكي نيست، دوست نداريد از آن استفاده كنيد. نكنيد! 
- مشكل DataProtection، استفاده از آن در محيط‌هاي ابري هست كه در هر لحظه سرويس ممكن است در يك سرور ديگر ارائه شود و كليدهاي رمزنگاري آن سرور فرق كند. قبلا از آن استفاده مي‌شد در اينجا كه مجبور شدم تغييرش بدم به روش فعلي كه از يك كليد ثابت و مشخص استفاده مي‌كند.
