### ISSUE TITLE
عدم نمایش کد امنیتی

### ISSUE THREAD

**Issue by amir3164** [VahidN/DNTCaptcha.Core#17]
<div dir="rtl">
با سلام 
من از  کل کد های شما رو  انتقال دادم و تمامی کلاس ها استفاده کردم و لی کد  امنیتیرو نشون نمیده
فقط من از Install-Package DNTCaptcha.Core استفاده نکرده از سورس کدها استفاده کردم. تمامی مراحل رو خط به خط اجرا کردم. ,ولی متاسفانه نمایش داده نمیشود.ایا قسمت خاصی رو باید بررسی کنم .ممنون

**Comment by VahidN** [comment]
<div dir="rtl">

ما امكان ديباگ از راه دور كدهاي شما را نداريم
بهتر است از بسته‌ي نيوگت ارائه شده استفاده كنيد تا به روز رساني‌هاي بعدي را هم دريافت كنيد
