### ISSUE TITLE
captcha refresh button does not work after absolute expiration. 

### ISSUE THREAD

**Issue by amirhosseini01** [VahidN/DNTCaptcha.Core#170]
# Summary of the issue
after absolute expiration, refresh button does not work. it sends request to server, but response will be 400 bad requests.
(Couldn't deserialize the model. Are you on a distributed environment? If yes, please read the `How to choose a correct storage mode` in the readme file.) and the only way that remains, is refresh the page.
is there any config or solution for this problem.
![dnt captcha error](https://github.com/VahidN/DNTCaptcha.Core/assets/49726420/89510816-ba91-419f-b6e2-f4a8a4695297)

## Environment

```
DNTCaptcha.Core version: 4.9.2
.NET Core SDK version: 7
```

## Example code/Steps to reproduce:

```
serviceCollection.AddDNTCaptcha(options =>
        {
            options.UseDistributedCacheStorageProvider()
                .UseDistributedCacheStorageProvider()
                .AbsoluteExpiration(minutes: 1)
                .ShowThousandsSeparators(false)
                .WithNoise(2f, 0.020f, 10, 1f)
                .WithEncryptionKey("")
                .InputNames(
                    new DNTCaptchaComponent
                    {
                        CaptchaHiddenInputName = "DNTCaptchaText",
                        CaptchaHiddenTokenName = "DNTCaptchaToken",
                        CaptchaInputName = "DNTCaptchaInputText"
                    })
                .Identifier("dntCaptcha")
                ;
        });
```

## Output:

```
Exception message: Couldn't deserialize the model. Are you on a distributed environment? If yes, please read the `How to choose a correct storage mode` in the readme file. 
(this message appears after ajax call of this URL: https://mydomain.com/DNTCaptchaImage/Refresh?data=encrypedData)
```

**Comment by VahidN** [comment]
Rebuilding the captcha is part of that info. If it's not available, it's not possible to recreate it again. In this case the user should refresh the whole page.
Don't choose 1 minute for it to expire. Choose a reasonable amount if time. 7 minutes is a good number. Our purpose is not to torture the real people.
