### ISSUE TITLE
The "RateLimit" counts twice the configured quantity

### ISSUE THREAD

**Issue by Qaemi66** [VahidN/DNTCaptcha.Core#174]
# Summary of the issue
I used the TestRazorPages project for testing and realized that the RateLimit in the DNTCaptcha.Core library is not working properly. For example, if we are allowed to retry 10 times, we can attempt 5 times. I tried to find the issue but couldn't. Please investigate.

```
DNTCaptcha.Core version: 4.9.3
.NET Core SDK version: 8.0
```

**Comment by VahidN** [comment]
When the captcha is being displayed it will count it too.
