### ISSUE TITLE
[feat] Custom Controller Name

### ISSUE THREAD

**Issue by IPdotSetAF** [VahidN/DNTCaptcha.Core#175]
# Summary of the issue

Please add a configuration for the `controller name` (or `Route`)

**Comment by VahidN** [comment]
why do you need this?

**Comment by IPdotSetAF** [comment]
Its natural to have the packages you use blend in with the rest of your software. It should not be sticking out.

The package is great, but has room to get even better. Thats all i m saying. ✌️
