### ISSUE TITLE
DNTCaptchaValidator does not validate get method

### ISSUE THREAD

**Issue by AlirezaSalimi1** [VahidN/DNTCaptcha.Core#18]
Hi,
I wanna use ValidateDNTCaptcha for a get method but when i do that whatever user enter in captcha input text box DNTCaptchaValidator consider that as true.

Is this part necessary in DNTCaptchaValidatorResult
![image](https://user-images.githubusercontent.com/35662310/41599461-8401f8c2-73e8-11e8-8bbc-c84706b66b5c.png)

**Comment by VahidN** [comment]
Yes for security reasons. Because `GET` requests are very easy for the data to leak through browser histories, or accidental link sharing.
https://stackoverflow.com/questions/5868786/what-method-should-i-use-for-a-login-authentication-request

**Comment by sunn789** [comment]
Hi I use Captcha the same as guide, 
1. because of bootstrap 4 glyphicon glyphicon-refresh not working.I change it to 'fas fa-sync-alt' but not work as btn
` asp-text-box-template="<div class='input-group'><div class='input-group-prepend'><span class='fa fa-lock'></span></div>{0}</div>"
                                         asp-validation-message-class="text-danger"
                                         asp-refresh-button-class="fas fa-sync-alt" />`
2. another setting is the same but validate not working, for ex: if write 1 instead announcement number if pass without error,

**Comment by VahidN** [comment]
- You will need [components-font-awesome](https://fontawesome.com/?from=io) for the `fa fa-lock` icon to work with [bootstrap 4](https://github.com/VahidN/DNTCaptcha.Core/issues/16#issuecomment-437611134).
- Client side validation needs some .js files which are mentioned in the readme file.

**Comment by hassan-gasemi** [comment]
Using ValidateDNTCaptcha on an action method in web api does not return error or terminate request. request model is implemented DNTCaptchaBase.

**Comment by VahidN** [comment]
This is [an Ajax form](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.TestWebApp/Views/Home/Index.cshtml#L36) sample with its [action method](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.TestWebApp/Controllers/HomeController.cs#L48).

**Comment by hassan-gasemi** [comment]
> This is [an Ajax form](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.TestWebApp/Views/Home/Index.cshtml#L36) sample with its [action method](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.TestWebApp/Controllers/HomeController.cs#L48).

Thanks. Key is ModelState.Maybe lack of info in readme document.
