### ISSUE TITLE
امکان انتخاب رنگ یکدست برای بک گراند

### ISSUE THREAD

**Issue by asde1373** [VahidN/DNTCaptcha.Core#184]
سلام
توی مستندات آپشنی برای اینکه رنگ بک گراند، gradient نباشه ندیدم و هر رنگی که ست میشه به صورت gradient میشه. امکان انتخاب رنگ solid وجود نداره؟

**Comment by VahidN** [comment]
خير قربان. هدف از كپچا اين هست كه كمي ناواضح باشه. 
اگر براي شما مناسب نيست، از آن استفاده نكنيد.
