### ISSUE TITLE
change image controller route template doen't work

### ISSUE THREAD

**Issue by ah-ezzat** [VahidN/DNTCaptcha.Core#186]
# Summary of the issue
I tried to change the image controller name instead of "DNTCaptchaImageController" to be "dnt" and the route template by adding a prefix "be-service/dnt/[action]"

  services.AddDNTCaptcha(options =>
  {
      options
          .UseCookieStorageProvider()
          .RateLimiterPermitLimit(10)
          .ShowExceptionsInResponse(true).ShowThousandsSeparators(false)
          .WithNoise(0.015f, 0.015f, 1, 0.0f).WithEncryptionKey("This is my secure key!")
          .WithNonceKey("NETESCAPADES_NONCE")
          .WithCaptchaImageControllerNameTemplate("dnt")
          .WithCaptchaImageControllerRouteTemplate("be-service/dnt/[action]");
  });

but i got the below issue, any other configuration needed?

## Environment

```
DNTCaptcha.Core version: 5.2.6
.NET Core SDK version: 8
IDE: VS 2022
```

## Example code/Steps to reproduce:

```
paste your core code
```

## Output:

```
Exception message:
Full Stack trace:
```
It's not possible to determine the URL of the `DNTCaptchaImageController.Show` method

**Comment by VahidN** [comment]
Probably it's because of https://github.com/VahidN/DNTCaptcha.Core/issues/181

**Comment by ah-ezzat** [comment]
it's deferent from #181, I don't see the same issue, 
the point here is i need to change the route template for DNT endpoints

**Comment by VahidN** [comment]
[It's not possible](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.Core/ControllerRoutingConvention.cs#L17) to have both of them at the same time. If it should be specified dynamically, swagger won't like it and vice-versa.

**Comment by ah-ezzat** [comment]
![image](https://github.com/user-attachments/assets/8a924e73-9878-4aa6-bc5b-aec4bfd2b3e7)

 I was able to change the routing controller template by removing 
 //[Route("[controller]")] 
 from DNTCaptchaImageController
