### ISSUE TITLE
مشکل در ریفرش کپچا پس از پایان زمان تنظیم شده در AbsoluteExpiration

### ISSUE THREAD

**Issue by Qaemi66** [VahidN/DNTCaptcha.Core#189]
# Summary of the issue
زمانی که کپچا لود میشود ریفرش آن بدرستی کار میکند اما وقتی منقضی میشود دیگر دکمه RefreshCaptcha با خطای 400 (badRequest) مواجه میشود

## Environment

```
DNTCaptcha.Core version: 5.2.7
.NET Core SDK version: 8.0
IDE: rider
```

## Example code/Steps to reproduce:

```
paste your core code
```

## Output:

```
Exception message:
Full Stack trace:
```

**Comment by VahidN** [comment]
بهتر است از اين كپچا استفاده نكنيد. اين كپچا براي كسانيكه قادر به بررسي خروجي developer tools مرورگر نيستند، مطلقا مناسب نيست.
