### ISSUE TITLE
RTL text direction issue on CentOS 7

### ISSUE THREAD

**Issue by saeedrahimi** [VahidN/DNTCaptcha.Core#19]
I run my project on centos 7 and I've installed all dependencies you referred in  README.md, the problem is that captcha image characters displaying on wrong direction. 
Also i installed Tahoma and other RTL fonts and it didn't worked.
have you any idea to solve this?

## Environment
```
The in-use version: DNTCaptcha.Core 1.4.4
Operating system: CentOS Linux 7
IDE: Published with Visual Studio 2017 (v15.6.5) on Windows 10
```

## Captcha URL:
```
http://192.168.228.129:5000/DNTCaptchaImage/Show?text=CfDJ8LWca3Bj7zxDmnTo3VBV6aSizgT3jEfA3aTyeat07C8MaMVgW0Xv7lZCeoV3VHONnTrV8iR8wjQZz04t0dgMVb5E%2Bion2y%2BiAVXzd%2F4sJq%2Fk50Ycex6noL8hxdF6XnJ81IsX7jNRq93UAPc4OOvIb6oAzmm2RKo1dy1R4XjUh3GlLcny19aJ2YrAW6xntViwHg%3D%3D&rndDate=636692528396190703&foreColor=%23333333&backColor=%23ccc&fontSize=20&fontName=Tahoma
```
## Output:
![show](https://user-images.githubusercontent.com/12451743/43772658-1410dd62-9a58-11e8-83a5-2c5977d194b2.png)

**Comment by VahidN** [comment]
RTL support has been added to [lib gdi plus recently ](https://github.com/mono/libgdiplus/pull/269#event-1752589112)and it will be part of the next System.Drawing package.
