### ISSUE TITLE
don't refresh request

### ISSUE THREAD

**Issue by pMonfared** [VahidN/DNTCaptcha.Core#2]
Hi

i found a problem in refresh button in identity page like Login or Register 
do not fire request to refresh captcha image

![image](https://cloud.githubusercontent.com/assets/10448255/23339579/14bb5100-fc3b-11e6-97d7-783f441b5e82.png)

**Comment by VahidN** [comment]
- Make sure you are using the latest version: 1.1.1
- Make sure you have included unobtrusive Ajax scripts:
   [bower.json](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.TestWebApp/bower.json#L9)
   [bundleconfig.json](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.TestWebApp/bundleconfig.json#L15)

**Comment by pMonfared** [comment]
I have problem in Area Controllers 

![image](https://cloud.githubusercontent.com/assets/10448255/23340389/8cc04ac0-fc4a-11e6-88a4-9e14775794c1.png)

**Comment by VahidN** [comment]
You are not using the latest version. It's fixed in V 1.1.1.

**Comment by pMonfared** [comment]
oh yes. sorry - fixed - thanks.
but how to refresh captcha manual with jquery commands?
