### ISSUE TITLE
Bad Request - Request Too Long

### ISSUE THREAD

**Issue by rezaeiy** [VahidN/DNTCaptcha.Core#21]
<div dir="rtl">

با سلام و احترام
زمانی در یک صفحه نیاز به وجود کپچاهای زیادی باشد مرورگر با خطای زیر مواجه میشه
Bad Request - Request Too Long
و برای ادامه کار حتما باید کش مرورگر پاک بشه

**Comment by VahidN** [comment]
If you have too many captha's on the page, you will need another method of storing its related data. This component uses [CookieCaptchaStorageProvider](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.Core/Providers/CookieCaptchaStorageProvider.cs) by default. You can change it by implementing the [ICaptchaStorageProvider](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.Core/Contracts/ICaptchaStorageProvider.cs) interface to use for instance an in-memory cache. And finally [use this new implementation](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.Core/CaptchaServiceCollectionExtensions.cs#L20)  instead of the default one.

**Comment by rezaeiy** [comment]
public class InmemoryCaptchaStorageProvider : ICaptchaStorageProvider
    {
        private readonly ICaptchaProtectionProvider _captchaProtectionProvider;
        private readonly ILogger<InmemoryCaptchaStorageProvider> _logger;
        private const int CookieLifeTimeInMinutes = 7;
        private IMemoryCache _memorycache;

        public InmemoryCaptchaStorageProvider(
            ICaptchaProtectionProvider captchaProtectionProvider,
            IMemoryCache memorycache,
            ILogger<InmemoryCaptchaStorageProvider> logger)
        {
            captchaProtectionProvider.CheckArgumentIsNull(nameof(captchaProtectionProvider));
            logger.CheckArgumentIsNull(nameof(logger));

            _captchaProtectionProvider = captchaProtectionProvider;
            _logger = logger;
            _memorycache = memorycache;
        }


        public void Add(HttpContext context, string token, string value)
        {
            value = _captchaProtectionProvider.Encrypt($"{value}{getCookieValueSalt(context)}");
            _memorycache.Set<string>(token, value, getMemoryCacheOptions());
        }


        public bool Contains(HttpContext context, string token)
        {
            if (!string.IsNullOrEmpty(_memorycache.Get<string>(token)))
            {
                return true;
            }
            return false;
        }

        public string GetValue(HttpContext context, string token)
        {
            string cookieValue;

            if (!_memorycache.TryGetValue<string>(token, out cookieValue))
            {
                _logger.LogInformation("Couldn't find the captcha cookie in the request.");
                return null;
            }
            _memorycache.Remove(token); 

            var decryptedValue = _captchaProtectionProvider.Decrypt(cookieValue);
            return decryptedValue?.Replace(getCookieValueSalt(context), string.Empty);
        }


        public void Remove(HttpContext context, string token)
        {
            if (!string.IsNullOrEmpty(_memorycache.Get<string>(token)))
            {
                _memorycache.Remove(token);
            }

        }


        private MemoryCacheEntryOptions getMemoryCacheOptions()
        {
            MemoryCacheEntryOptions options = new MemoryCacheEntryOptions();
            options.AbsoluteExpiration = DateTime.Now.AddMinutes(CookieLifeTimeInMinutes);
            options.SlidingExpiration = TimeSpan.FromMinutes(CookieLifeTimeInMinutes);

            return options;
        }

        private string getCookieValueSalt(HttpContext context)
        {
            var ip = context.Connection.RemoteIpAddress;
            var userAgent = (string)context.Request.Headers[HeaderNames.UserAgent];
            var issueDate = DateTime.Now.ToString("yyyy_MM_dd", CultureInfo.InvariantCulture);
            var name = typeof(InmemoryCaptchaStorageProvider).Name;
            var salt = $"::{issueDate}::{name}::{ip}::{userAgent}";
            return _captchaProtectionProvider.Hash(salt);
        }
    }
در صورت استفاده از کلاس فوق مشکل حل میشه
فقط سوالی که پیش میاد آیا در صورت استفاده از این کد مشکل کمبود حافظه پیش نمیاد؟
اگر جواب مثبت است آیا راهی برای رفع مشکل وجود دارد؟
با تشکر

**Comment by VahidN** [comment]
Version 1.6 supports more storage providers
```csharp
using DNTCaptcha.Core;

namespace DNTCaptcha.TestWebApp
{
    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddDNTCaptcha(options => options.UseCookieStorageProvider());
        }
```
