### ISSUE TITLE
مشکل در لود نشدن عکس کپچا

### ISSUE THREAD

**Issue by ghost** [VahidN/DNTCaptcha.Core#22]
همه روشهایی که گفته شد رو انجام دادم ،  اتریبیوت ها هم درست کار میکنن . اما در ویو عکس لود نمیشه
![screenshot 88](https://user-images.githubusercontent.com/16300201/46806698-1b701c80-cd75-11e8-8079-7255457d37c8.png)

**Comment by VahidN** [comment]
- run your web application using the `dotnet watch run` command and the watch its output, its logs to see if there are any errors at there.
- open the `developers console` of your web browser and check out its reported errors.
