### ISSUE TITLE
استفاده دو کپچا به صورت همزمان در یک صفحه

### ISSUE THREAD

**Issue by javadmjt** [VahidN/DNTCaptcha.Core#23]
سلام واحترام 
در کروم زمانی که از دو کپچا به صورت همزمان در یک صفحه استفاده میکنم با خطای
```
Found 2 elements with non-unique id #DNTCaptchaInputText
```

مواجه میشم

**Comment by VahidN** [comment]
مهم نيست و كاملا آزمايش شده. اين المان‌ها داخل فرم قرار مي‌گيرند و مستقل پردازش مي‌شوند
