### ISSUE TITLE
can you provide some way for me to extend other language？

### ISSUE THREAD

**Issue by jingliancui** [VahidN/DNTCaptcha.Core#24]
Hi，
I found that there is only 3 language support.
Is there provide any other way for me to add other language support ?

**Comment by VahidN** [comment]
You can follow this pull request to see how to add a new language support:
https://github.com/VahidN/DNTCaptcha.Core/pull/20/files

**Comment by jingliancui** [comment]
Got it, Thanks so much.I will try it. and if you can update this feature for others to extend their language this project will become better and better : )
