### ISSUE TITLE
problem with ajax  post request

### ISSUE THREAD

**Issue by amir3164** [VahidN/DNTCaptcha.Core#25]
<div dir="rtl">

با سلام
ایا کد کپچا با درخواست  های اژاکسی مشکل دارد 
با این حطا مواجه شدم. با تشکر.
</div>

```
NotSupportedException: Your ViewModel should implement the DNTCaptchaBase class (public class AccountViewModel : DNTCaptchaBase {}).
```

**Comment by VahidN** [comment]
<div dir="rtl">

پيام خطا واضح هست. از [اين كلاس](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.TestWebApp/Models/AccountViewModel.cs#L6) ايده بگيريد
