### ISSUE TITLE
Incompatibility with .net core 2.2

### ISSUE THREAD

**Issue by GhalamborM** [VahidN/DNTCaptcha.Core#27]
ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index
System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
System.Collections.Generic.List<T>.get_Item(int index)
Microsoft.AspNetCore.Mvc.Routing.UrlHelper.GetVirtualPathData(string routeName, RouteValueDictionary values)
Microsoft.AspNetCore.Mvc.Routing.UrlHelper.Action(UrlActionContext actionContext)
Microsoft.AspNetCore.Mvc.UrlHelperExtensions.Action(IUrlHelper helper, string action, string controller, object values, string protocol)
DNTCaptcha.Core.DNTCaptchaTagHelper.getCaptchaImageTagBuilder(string encryptedText)
DNTCaptcha.Core.DNTCaptchaTagHelper.Process(TagHelperContext context, TagHelperOutput output)
DNTCaptcha.Core.DNTCaptchaTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.RunAsync(TagHelperExecutionContext executionContext)

AspNetCore.Views_Account_Login.<ExecuteAsync>b__45_1() in Login.cshtml
-
                            <dnt-captcha asp-captcha-generator-max="9000"
                                         asp-captcha-generator-min="1"
                                         asp-captcha-generator-language="Persian"
                                         asp-placeholder="کد امنیتی به رقم (مانند: 1388)"
                                         asp-validation-error-message="لطفا کد امنیتی را به رقم وارد نمائید"
                                         asp-font-name="Tahoma"
                                         asp-font-size="18"
                                         asp-fore-color="#333333"
                                         asp-back-color="#ccc"
                                         asp-text-box-class="k-textbox"
                                         asp-text-box-template="<span class='k-textbox k-space-right w-100 border-danger'>{0}<span class='inputgroup-icon ms-Icon  ms-Icon--Lock'></span></span>"
                                         asp-validation-message-class="text-danger"
                                         asp-refresh-button-class="ms-Icon ms-Icon--Refresh btn-sm" />

**Comment by VahidN** [comment]
Fixed via #https://github.com/VahidN/DNTCaptcha.Core/commit/4fb6f014917f1e9e7c47215e60d58d8fd1580344
