### ISSUE TITLE
رفرش کد کپچا

### ISSUE THREAD

**Issue by amir3164** [VahidN/DNTCaptcha.Core#30]
با سلام 
برای درخواست های  که خروجی  جی سان هست  مقدار کپچا  تغییر نمیکند . وقتی کد کپچا رو اشتباه وارد میکند  دوباره کد  تغییر نمی کند .با چه روشی کپچا رو رفرش کنیم .ممنون

> `   return Json(new { success = false, state = "loginFail", responseText = messages });`
من اونطوری فراخوانی کردم حالا نمیدونم روش کارم درسته یا خیر
`$("#dntCaptchaRefreshButton").trigger("click");`

**Comment by VahidN** [comment]
<div dir="rtl">

من حالت جي‌سون را براي انگيولار اضافه كردم و [مثالش اينجا](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.AngularClient/src/app/dnt-captcha/dnt-captcha.component.ts#L68) هست
