### ISSUE TITLE
observable error:  HttpErrorResponse Bad Request

### ISSUE THREAD

**Issue by daliri72** [VahidN/DNTCaptcha.Core#31]
# observable error:  HttpErrorResponse
I use DNTCaptcha.Core Version="1.4.1" and call it in Startup.cs like this
```
 services.AddDNTCaptcha();
```
In my angular app use dnt-captcha component

When I run project angular show this error in console of browser

```
observable error:  HttpErrorResponse {headers: HttpHeaders, status: 400, statusText: "Bad Request", url: "http://localhost:5000/DNTCaptchaApi/CreateDNTCaptcha", ok: false, …}
```
How can I solve this problem?

**Comment by VahidN** [comment]
V1.4.1 is not supported anymore. update your dependencies to **V1.6.6**.
