### ISSUE TITLE
Bypassing Captcha using Refresh button

### ISSUE THREAD

**Issue by SSgumS** [VahidN/DNTCaptcha.Core#35]
# Summary of the issue
_Refresh_ button explicitly sets model properties from query strings and generates captcha based on it.
It results in a vulnerability that by using _Min_ and _Max_ properties in url of refresh button, we can generate our desired value and it will validate successfully.

## Example code/Steps to reproduce:
See this _data-ajax-url_ attribute of refresh button for example:
`data-ajax-url="/DNTCaptchaImage/Refresh?rndDate=637025421369768143&FontName=Tahoma&FontSize=12&ForeColor=%231B0172&Language=Persian&Max=999&Min=100&Placeholder=%D8%AD%D8%A7%D8%B5%D9%84%20%D8%AC%D9%85%D8%B9%20%D8%A7%D8%B9%D8%AF%D8%A7%D8%AF%20%D8%A8%D8%A7%D9%84%D8%A7%20%D8%B1%D8%A7%20%D9%88%D8%A7%D8%B1%D8%AF%20%DA%A9%D9%86%DB%8C%D8%AF&TextBoxClass=text-box%20single-line%20mx-auto&TextBoxTemplate=%7B0%7D&ValidationErrorMessage=%D9%84%D8%B7%D9%81%D8%A7%20%DA%A9%D8%AF%20%D8%A7%D9%85%D9%86%DB%8C%D8%AA%DB%8C%20%D8%B1%D8%A7%20%D8%A8%D9%87%20%D8%B1%D9%82%D9%85%20%D9%88%D8%A7%D8%B1%D8%AF%20%D9%86%D9%85%D8%A7%D8%A6%DB%8C%D8%AF&ValidationMessageClass=text-danger&CaptchaToken=.dntCaptcha95e784a1ee6e1f5c8252046ba44a97965b0484985984548&RefreshButtonClass=glyphicon%20glyphicon-refresh%20btn-sm"`

we can change it to this (Max=999&Min=999):
`data-ajax-url="/DNTCaptchaImage/Refresh?rndDate=637025421369768143&FontName=Tahoma&FontSize=12&ForeColor=%231B0172&Language=Persian&Max=999&Min=999&Placeholder=%D8%AD%D8%A7%D8%B5%D9%84%20%D8%AC%D9%85%D8%B9%20%D8%A7%D8%B9%D8%AF%D8%A7%D8%AF%20%D8%A8%D8%A7%D9%84%D8%A7%20%D8%B1%D8%A7%20%D9%88%D8%A7%D8%B1%D8%AF%20%DA%A9%D9%86%DB%8C%D8%AF&TextBoxClass=text-box%20single-line%20mx-auto&TextBoxTemplate=%7B0%7D&ValidationErrorMessage=%D9%84%D8%B7%D9%81%D8%A7%20%DA%A9%D8%AF%20%D8%A7%D9%85%D9%86%DB%8C%D8%AA%DB%8C%20%D8%B1%D8%A7%20%D8%A8%D9%87%20%D8%B1%D9%82%D9%85%20%D9%88%D8%A7%D8%B1%D8%AF%20%D9%86%D9%85%D8%A7%D8%A6%DB%8C%D8%AF&ValidationMessageClass=text-danger&CaptchaToken=.dntCaptcha95e784a1ee6e1f5c8252046ba44a97965b0484985984548&RefreshButtonClass=glyphicon%20glyphicon-refresh%20btn-sm"`

It will give us 999 and when we write 999 in input, it will validate successfully.
A hacker can easily bypass captcha this way.
Refresh controller action must not depend on anything received from client and must generate captcha independently based on sever-side values.

**Comment by VahidN** [comment]
Thanks for reporting it. It's fixed via #https://github.com/VahidN/DNTCaptcha.Core/commit/b2ed972575ea13ccba8e6dab365e1cba993ad86c
