### ISSUE TITLE
Reusability of Captcha during Expiration time

### ISSUE THREAD

**Issue by SSgumS** [VahidN/DNTCaptcha.Core#36]
# Summary of the issue
Each captcha has its specific hidden inputs (2 ones), id, and cookie and maybe other things that I don't know.
These combinations with their original answer make a captcha valid. Unfortunately, each captcha expires just when its expiration time reaches. This will results a situation that captcha will be reusable in all its expiration time (approximately 8 minutes).
Right behavior is that each time a captcha is checked, its token and all stuffs related must expire.

## Example code/Steps to reproduce:
Save the _cookie_ in your browser. Write right answer in _value_ attribute of the main _input_ and copy the parent _div_ with all things within it.
During the expiration time, the captcha remains reusable and you can use these combinations (Cookie and HTML node) to validate all your requests.

**Comment by VahidN** [comment]
[It will be expired after validation](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.Core/Providers/DNTCaptchaValidatorService.cs#L171).

**Comment by SSgumS** [comment]
Tnx. You are right. I was using an older version of your library. Sorry for my carelessness.

**Comment by VahidN** [comment]
If you want to use 100% server side tracked tokens, you can use [other storage modes](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.TestWebApp/Startup.cs#L28).
