### ISSUE TITLE
bad request error

### ISSUE THREAD

**Issue by GhalamborM** [VahidN/DNTCaptcha.Core#37]
تونسخه 1.9.2 این خطا اتفاق می افته

HTTP400: BAD REQUEST - The request could not be processed by the server due to invalid syntax.

**Comment by sunn789** [comment]
من هم بارگذاری کردم ورژن جدید را علاوه بر اینکه کپچای قبلی از کار افتاد اصلا نمایش داده نمیشد، هر چند در سورس صفحه نمایش داده میشد

**Comment by VahidN** [comment]
<div dir="rtl">

تمام قسمت‌هايي رو كه مشخص كرده بودم حذف كرديد
اين توضيحات براي بررسي كافي نيست

**Comment by VahidN** [comment]
<div dir="rtl">

قالبي براي ارسال مشكل طراحي شده بود كه حذفش كرديد. بعد الان من بايد تك تك بپرسم كه محيط چي هست فريم ورك چي هست كدت چي هست
