### ISSUE TITLE
HTTP400: BAD REQUEST

### ISSUE THREAD

**Issue by GhalamborM** [VahidN/DNTCaptcha.Core#38]
# Summary of the issue
سلام
روی دو تا پروژه ی ساده تازه ایجاد شده
net core 2.2 , net 4.8 
تست کردم باز همین خطا رو داد

این دلیلش بود که تو باگ ایجاد شده قبلی جزییات نفرستادم

## Environment
edge 44 , firefox 69 developer
```
DNTCaptcha.Core version:  1.9.2
.NET Core SDK version:  net core 2.2  , net framework 4.8
IDE: visual studio  16.2.3
```

## Example code/Steps to reproduce:

```
paste your core code
```

## Output:
HTTP400: BAD REQUEST - The request could not be processed by the server due to invalid syntax.
GET - https://localhost:44333/DNTCaptchaImage/Show/CfDJ8DB9vg-EjNhHuYHkC4MDpXn9FS2k-ZuzzPnJ3rx9b2LbtrW-LuVgUrzapIYMrdlJNA6n9s5JUjTAQE8RLmfu8fUFpXgzlSMJR7KcCT6l51xuadDw1-m-qBDI2MkcocksgVA1J5IQoCygwBam-7adM0UE2b5hDZ7ogXt7iFlU90zikYz9NPQpXlFz-UV5bPAF6_CMqytNTvtZDvBjv_WVLCrqcKJdUG68I2CcaM8mdvkBEt5OOyFOq4afytCQO5HUs7MNiRX228CBfiOvRmRQvToIJXLqYgMyN91joznk6VMFBA2f_i8rlIV_8NjE2HtUrRn-XkADFrNZ8DyJ_uVW9Skm308-DADunJhR12urEiRzKez_X1UEv7Z_t6MuANTk8AlU8NwOqKnTjh8zr7PDvljpYbgBeC2DkEGIWqOORK7nvzm9NOqfbYdKZLOI15TmCMF7hD2Al_2MfD-bhT9I1R_lTZbAz_OFdO-xTU16IO_jBbOGLTStryslYPNHrptoYg
```
Exception message:
The request could not be processed by the server due to invalid syntax.

Full Stack trace: نداره!
```

**Comment by VahidN** [comment]
<div dir="rtl">

لطفا پروژه‌ي تازه ايجاد شده را اينجا پيوست كنيد براي بررسي بيشتر. فايل زيپ آن‌را درگ و دراپ كنيد روي همين اديتور

**Comment by GhalamborM** [comment]
[WebApplication4.zip](https://github.com/VahidN/DNTCaptcha.Core/files/3552796/WebApplication4.zip)

**Comment by VahidN** [comment]
<div dir="rtl">

هر دو مثال شما براي من قابل اجرا است

![cpt](https://user-images.githubusercontent.com/766010/63891958-a8f34400-c9fb-11e9-9528-ef7eaa52fc56.png)

البته من از دستور dotnet run براي اجرا استفاده مي‌كنم

**Comment by GhalamborM** [comment]
<p dir="rtl">
بله درست میگید با donet run درست کار کرد
اما با خود ویژوال استودیو که اجرا میکنم خطا میده
</p>
![image](https://user-images.githubusercontent.com/11071463/63892217-57978480-c9fc-11e9-90f5-aeccb99f1dea.png)

**Comment by VahidN** [comment]
Fixed it via #https://github.com/VahidN/DNTCaptcha.Core/commit/14f7b60b7a357d2c21e2e084d6d91d05ea60f28d

**Comment by VahidN** [comment]
Thanks. Fixed it via #https://github.com/VahidN/DNTCaptcha.Core/commit/e21394962f97a7a9d906f77e8603d82f5bd03e39
