### ISSUE TITLE
Conflict with Content-Security-Policy

### ISSUE THREAD

**Issue by ARoshanZamir** [VahidN/DNTCaptcha.Core#41]
## Environment

```
DNTCaptcha.Core version: 2.0.2
.NET Core SDK version: 2.2.0
```
If we enable ```Content-Security-Policy``` on our website , we will get an error  because of DNTCaptcha (it refers to not to put script tag in your page ).

DNTCaptcha puts a script tag in the page . 
Is there any way to solve this problem ?

**Comment by VahidN** [comment]
Yes. Don't use it. Thank you.
