### ISSUE TITLE
مشکل در دکمه refresh

### ISSUE THREAD

**Issue by ni-fara** [VahidN/DNTCaptcha.Core#42]
<div dir="rtl">

سلام، این مشکل قبلا توسط https://github.com/VahidN/DNTCaptcha.Core/issues/15 گزارش داده شده و شما هم راه حلش رو ارائه دادید.
منتها از اونجا که برای من هم مجدد پیش اومد و مدت زمانی طول کشید تا در نهایت به قسمت ایرادات مخزن سر زدم و متوجه راه حل رفع کردنش شدم، جهت صرفه جویی در وقت سایر برنامه نویسان که ممکنه در آینده به این مشکل برخورد کنند بهتر هست که قسمت راهنمای پروژه رو به روز رسانی کنید.

با توجه به اینکه استفاده از نسخه CDN
`<script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/mvc/3.0/jquery.unobtrusive-ajax.min.js"></script>`
باعث ایجاد مشکل میشه بهتر هست اون قسمت رو از راهنما حذف کنید، یا صریحا در راهنما اعلام کنید که ایجاد مشکل میکنه.

چند نکته:
1-نسخه
[NPM](https://www.npmjs.com/package/jquery-ajax-unobtrusive)
موجود هست میتونید به راهنما اضافه کنید. من با استفاده از
libman
اضافش کردم به پروژم بدون مشکل کار میکرد.
2-نسخه
[cdnjs](https://github.com/cdnjs/cdnjs/pull/13029)
در حال ایجاد شدن هست
3-آدرسی که برای پروژه
[https://github.com/aspnet/jquery-ajax-unobtrusive/tree/master/dist](https://github.com/aspnet/jquery-ajax-unobtrusive/tree/master/dist)
در راهنمای سایت گذاشتید خطای 404 میده،
به مخزن اصلی تغییرش بدید
[https://github.com/aspnet/jquery-ajax-unobtrusive/](https://github.com/aspnet/jquery-ajax-unobtrusive/)

با تشکر

**Comment by VahidN** [comment]
Udated the readme file.
