### ISSUE TITLE
Can be used without AddMvc()?

### ISSUE THREAD

**Issue by Esniper90** [VahidN/DNTCaptcha.Core#43]
Is it possible to use this library without adding full MVC (services.AddMvc() in Startup.cs)? for example i want to just use AddControllers()

**Comment by VahidN** [comment]
If you don't want to use its tag-helper, yes.

**Comment by Esniper90** [comment]
when i use AddControllers() with this configuration:
`services.AddDNTCaptcha(options => options.UseMemoryCacheStorageProvider());`
i get this error and image not shown:

ActionDescriptor: `'DNTCaptcha.Core.DNTCaptchaImageController.Show (DNTCaptcha.Core)'`

Exception: `Unable to resolve service for type 'Microsoft.AspNetCore.Mvc.ViewFeatures.ITempDataProvider' while attempting to activate 'DNTCaptcha.Core.DNTCaptchaImageController'`

**Comment by VahidN** [comment]
```csharp
services.AddControllers().AddCookieTempDataProvider();
```
