### ISSUE TITLE
NO Support for Distributed Systems

### ISSUE THREAD

**Issue by SSgumS** [VahidN/DNTCaptcha.Core#44]
# Summary of the issue
The library doesn't support distributed systems.
It's such a waste that a good library like this doesn't have this feature.

# Probable Solution
I had a look at the source code and it seems that adding this feature doesn't need so much effort.
`IMemoryCache` has been used in two files:
`MemoryCacheCaptchaStorageProvider` and `SerializationProvider`
The latter one prevent any storage provider to work on distributed system.
I don't know what other changes is required but at least I know one part of the change required to support the feature is to just replace `IMemoryCache` with `IDistributedCache`.

**Comment by VahidN** [comment]
You can add your custom `ICaptchaStorageProvider` using the [UseCustomStorageProvider<T>()](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.Core/Contracts/DNTCaptchaOptions.cs#L17) method.

**Comment by SSgumS** [comment]
We can use SessionStorageProvider for distributed systems. But `SerializationProvider` has been used in all of storage providers.

**Comment by SSgumS** [comment]
To be more accurate, `StorageProvider` is not related to `SerializationProvider`. You can see `Refresh` action method in `DNTCaptchaImageController`. It uses `SerializationProvider`.

**Comment by VahidN** [comment]
`SerializationProvider` is replaceable. Everything here works through the [dependency injection](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.Core/CaptchaServiceCollectionExtensions.cs#L45) system:
```C#
services.TryAddSingleton<ISerializationProvider, SerializationProvider>();
```
When we have **Try**AddSingleton, it means if you add your own `ISerializationProvider` before the `AddDNTCaptcha` method, your version will be used automatically.

**Comment by SSgumS** [comment]
It's ok. Thanks.
I know that I could replace it. I just wanted to help to make the library better. Beside that, I didn't know exactly what piece of the library is not appropriate for distributed systems (I'm not the coder of this library). So, I wanted to give you a signal that if you can add support for this feature, It's appreciated. I think it worth the effort and it seems that it's not much difficult (I'm not sure. This uncertainty is what that prevent me from just replacing the `SerializationProvider`. Maybe it won't be enough)

**Comment by VahidN** [comment]
Added it via #https://github.com/VahidN/DNTCaptcha.Core/commit/b4e4d3184b66fbe6f4f8c6a118e71b9a57c7879e
