### ISSUE TITLE
خواندن توسط google lens

### ISSUE THREAD

**Issue by rbsdotnet** [VahidN/DNTCaptcha.Core#45]
<div dir="rtl">

سلام جناب نصیری
من از این بسته برای یک وب سایت سازمانی استفاده کردم
امنیت سازمان بهم گفته که میشه با نرم افزار google lens کد رو خواند آیا راهی وجود داره که این اتفاق نیفته؟

**Comment by VahidN** [comment]
<div dir="rtl">

- اين پروژه سورس باز هست. در آن مشاركت كنيد
- حالت‌ها و متون فارسي آن‌را كه احتمالا قابل خواندن نيستند هم بررسي كنيد
- كاربر را هم زجر كش نكنيد با سخت كردن تشخيص آن.

**Comment by rbsdotnet** [comment]
<div dir="rtl">
جناب نصیری میشه راهنمایی کنید که کدوم قسمت از کد شما رو باید تغییرات ایجاد کنم؟
واینکه در کدوم بخش میتونم خطوط اضافه کنم؟
