### ISSUE TITLE
پیشنهاد ساختار جدید به همراه نویز

### ISSUE THREAD

**Issue by rbsdotnet** [VahidN/DNTCaptcha.Core#46]
<div dir="rtl">
جناب نصیری سلام و عرض ادب
من ساختار جدید رو ایجاد کردم
میخواستم روی پروژه شما PR کنم متاسفانه نتونستم
اگر ایرادی نداره من این بخش رو برای شما میفرستم در صورت تایید در نسخه بعدی به صورت پارامتر قرار بدید که به صورت ساده یا دارای نویز
سپاس
</br>
</br>
[DNTCaptcha.Core-master.zip](https://github.com/VahidN/DNTCaptcha.Core/files/4270918/DNTCaptcha.Core-master.zip)

**Comment by rbsdotnet** [comment]
<div dir="rtl">
افزودن پارامتر use-noise در TagHelper
ایجاد شرط در صورت داشتن پارامتر usenoise فراخوانی متد جدید در کلاس CaptchaImageProvider
متد جدید با ساختار زیر
</br>
</br>
<div dir="ltr">
`byte[] DrawCaptcha(string message, string foreColor, float fontSize, string fontName)`

**Comment by rbsdotnet** [comment]
<div dir="rtl">
جناب نصیری PR ایجاد شد

**Comment by VahidN** [comment]
<div dir="rtl">

ممنون. به زودي اعمال مي‌شود

**Comment by rbsdotnet** [comment]
@VahidN 
<div dir="rtl">
سلام جناب نصیری
ساختار Noise رو تغییر دادم چون چندین پیشنهاد دریافت کردم که کمی ناخوانا می باشد
یک نمونه از ساختار جدید
![image](https://user-images.githubusercontent.com/49598914/78619756-76fc6700-7893-11ea-8397-747987a0f0ba.png)

**Comment by VahidN** [comment]
<div dir="rtl">

اين هم خوبه. احتمالا بايد امكان انتخاب بين اين‌ها فراهم شود.

**Comment by rbsdotnet** [comment]
<div dir="rtl">
پس من یک خصوصیت به صورت نسخه بندی اضافه میکنم

**Comment by VahidN** [comment]
<div dir="rtl">

كاري شبيه به [DisplayMode](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.Core/CaptchaServiceCollectionExtensions.cs#L31) بايد انجام شود
