### ISSUE TITLE
Error 500 without description

### ISSUE THREAD

**Issue by Alirezanet** [VahidN/DNTCaptcha.Core#48]
# Summary of the issue
I'm trying to use this library but I'm facing an HTTP 500 error. 
the expected behavior is a useful error message.

## Environment
Linux
```
DNTCaptcha.Core version: 2.3.0
.NET Core SDK version: 3.1
```

## Example code/Steps to reproduce:
example request headers:

:method: POST
:path: /DNTCaptchaApi/CreateDNTCaptcha
:scheme: https
accept: application/json, text/plain, */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
cache-control: no-cache
content-length: 210
content-type: application/json;charset=UTF-8
origin: https://localhost:5001
pragma: no-cache
referer: https://localhost:5001/login
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
 
example request payload:

```json
{"backColor":"#f7f3f3","fontName":"Tahoma","fontSize":18,"foreColor":"#111111","language":"English","max":9000,"min":1,"useRelativeUrls":true,"displayMode":"NumberToWord","useNoise":true,"captchaToken":"token"}
```

I've added library API this way : 
```csharp
services.AddDNTCaptcha(options =>
    options.UseCookieStorageProvider() // -> It relies on the server and client's times. It's ideal for 
    scalability, because it doesn't save anything in the server's memory. );
```

## Output:
Error 500.
```
Exception message: none
```
did I miss something?

**Comment by VahidN** [comment]
I added an API only [sample here](https://github.com/VahidN/DNTCaptcha.Core/tree/master/src/DNTCaptcha.TestApiApp), with this [HTML file](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.TestApiApp/wwwroot/index.html).
