### ISSUE TITLE
Refresh button not working after expiration time

### ISSUE THREAD

**Issue by SSgumS** [VahidN/DNTCaptcha.Core#51]
# Summary of the issue
After 7 minutes that captcha token is expired, Refresh button will be broken too.
This results in a situation that user gets stuck in login form and don't know why each captcha value is being rejected.

## Probable Solution
I don't know why it's necessary to set expiration time for `RefreshData`. I thinks it has happened by mistake. If `RefreshData` doesn't have an expiration time, everything is solved (without any security risks). Maybe our serialization providers should have an overload method for `Serialize` that doesn't set any expiration time. Then we can use that method for such data like `RefreshData` and use the main one for data that needs expiration time.

**Comment by VahidN** [comment]
It seems you don't like this component. I'm not going to change any of its settings. If a user can't pass a login form after 7 minutes, let it be. something is wrong with that person.

P.S.
I don't want to hear anything from you here again. Just don't use it. Thank you.
