### ISSUE TITLE
Image Provider generates Empty captcha (Linux)

### ISSUE THREAD

**Issue by Alirezanet** [VahidN/DNTCaptcha.Core#53]
# Summary of the issue
I have used this library on arch Linux before and it was working fine. yesterday i switch to Ubuntu 20.04 ( WSL2 windows 2004) and setup new development environment on my main machine everything is working fine except this library. 
there is no exception but the output of `DNTCaptchaImage/Show?...` is a empty transparent Image!
i already installed `libgdiplus` library on ubuntu. 
**what possibly can cause this problem ?** (look at attached image pls) 

## Environment
Wsl2 - Ubuntu 20.04

```
DNTCaptcha.Core version: 2.3.0 and 2.5.0
.NET Core SDK version:  3.1
IDE: vscode
```
## Output:
![unknown](https://user-images.githubusercontent.com/7004080/83509662-0794a380-a4e1-11ea-9bf8-b4ceb4e0792f.png)

```
Exception message: there is no exception
 ```

**Comment by VahidN** [comment]
Probably installing just `libgdiplus` is not enough. Try installing its required dependencies too:
```sh
    apt-get install libc6-dev libx11-dev
    apt-get install libgdiplus
    cd /usr/lib
    ln -s libgdiplus.so gdiplus.dll
    rm -rf /var/lib/apt/lists/*
```

**Comment by Alirezanet** [comment]
> Probably installing just `libgdiplus` is not enough. Try installing its required dependencies too:
> 
> ```shell
>     apt-get install libc6-dev libx11-dev
>     apt-get install libgdiplus
>     cd /usr/lib
>     ln -s libgdiplus.so gdiplus.dll
>     rm -rf /var/lib/apt/lists/*
> ```

unfortunately nothing is changed. could be this issue related to fonts somehow?

**Comment by SajjadHosseinPour** [comment]
any update on this issue? 
i've Just updated from version 2.3.0 to 2.5.0 
and captcha doesnt show any more.
dont know if the new version includes some breaking changes

**Comment by VahidN** [comment]
There's [a working sample here](https://github.com/VahidN/DNTCaptcha.Core/tree/master/src/DNTCaptcha.TestWebApp.V3x). give it a try. Also the [readme file](https://github.com/VahidN/DNTCaptcha.Core/blob/master/README.md) shows the latest changes.

**Comment by Alirezanet** [comment]
what about the main issue? 

I think there are three possibilities.
1. some other unknown dependencies are missing
2. this is a `libgdiplus` bug 
3. this is a DntCaptcha bug

any thoughts?

**Comment by VahidN** [comment]
Do you see an errors/exceptions in the console or debug window? (the same as the posted image)

**Comment by Alirezanet** [comment]
> Do you see any errors/exceptions in the console or debug window of your .NET Core app? (the same as the posted image)

unfortunately not at all.  

![Annotation 2020-06-07 112431](https://user-images.githubusercontent.com/7004080/83962414-61ff7c80-a8b2-11ea-985d-94eca01136e9.png)

**Comment by Alirezanet** [comment]
I also upgraded to `2.5.0`. the same problem exists yet.  (still just on ubuntu)

**Comment by Alirezanet** [comment]
I completely checked `libgdiplus ` dependencies and looks like everything is resolved:

`	linux-vdso.so.1 (0x00007ffc57989000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fcfe413e000)
	libcairo.so.2 => /lib/x86_64-linux-gnu/libcairo.so.2 (0x00007fcfe401b000)
	libfreetype.so.6 => /lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007fcfe3f5c000)
	libjpeg.so.8 => /lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007fcfe3ed7000)
	libtiff.so.5 => /lib/x86_64-linux-gnu/libtiff.so.5 (0x00007fcfe3e56000)
	libgif.so.7 => /lib/x86_64-linux-gnu/libgif.so.7 (0x00007fcfe3e4b000)
	libpng16.so.16 => /lib/x86_64-linux-gnu/libpng16.so.16 (0x00007fcfe3e11000)
	libX11.so.6 => /lib/x86_64-linux-gnu/libX11.so.6 (0x00007fcfe3cd4000)
	libexif.so.12 => /lib/x86_64-linux-gnu/libexif.so.12 (0x00007fcfe3c8d000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fcfe3c6a000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fcfe3b1b000)
	libfontconfig.so.1 => /lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007fcfe3ad4000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fcfe38e0000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fcfe386d000)
	libpixman-1.so.0 => /lib/x86_64-linux-gnu/libpixman-1.so.0 (0x00007fcfe37c6000)
	libxcb-shm.so.0 => /lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007fcfe37c1000)
	libxcb.so.1 => /lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fcfe3797000)
	libxcb-render.so.0 => /lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007fcfe3788000)
	libXrender.so.1 => /lib/x86_64-linux-gnu/libXrender.so.1 (0x00007fcfe357c000)
	libXext.so.6 => /lib/x86_64-linux-gnu/libXext.so.6 (0x00007fcfe3567000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fcfe354b000)
	libwebp.so.6 => /lib/x86_64-linux-gnu/libwebp.so.6 (0x00007fcfe32e2000)
	libzstd.so.1 => /lib/x86_64-linux-gnu/libzstd.so.1 (0x00007fcfe3239000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fcfe3212000)
	libjbig.so.0 => /lib/x86_64-linux-gnu/libjbig.so.0 (0x00007fcfe3002000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fcfe2ffc000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fcfe42f7000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fcfe2fce000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007fcfe2fc5000)
	libXau.so.6 => /lib/x86_64-linux-gnu/libXau.so.6 (0x00007fcfe2fbf000)
	libXdmcp.so.6 => /lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fcfe2fb5000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007fcfe2f9b000)
`

**Comment by Alirezanet** [comment]
finally, I think found the problem : 

is this decrypted value normal
? 
![Annotation 2020-06-07 215325](https://user-images.githubusercontent.com/7004080/83975453-53907f80-a909-11ea-818f-cf33168c0d8b.png)

**Comment by VahidN** [comment]
I will change the encryption part tomorrow. It seems a lot of ppl have problem with this part.

**Comment by Alirezanet** [comment]
> I will change the encryption part tomorrow. It seems a lot of ppl have problem with this part.
thanks. but I don't think the encryption part is wrong. a few hours ago I deleted my comments about encryption after I tested everything manually. in my opinion, the only part of this code that could cause this problem is the `DrawCaptcha` method. but maybe I'm wrong.

**Comment by Alirezanet** [comment]
any update on this issue?

**Comment by VahidN** [comment]
- No. I'm not using WSL/2 and I don't have any intention to even install it or try it.
- This is an open source project, feel free to move it forward.
