### ISSUE TITLE
Refresh do not work in ASP.NET core 3.0

### ISSUE THREAD

**Issue by kajaljain** [VahidN/DNTCaptcha.Core#54]
# Summary of the issue
When I click on refresh button url changes but captcha image do not change

## Environment
```
DNTCaptcha.Core version: 
.NET Core SDK version:  3.0 
```

**Comment by VahidN** [comment]
Have you added its dependencies?
- This library uses unobtrusive Ajax library for the refresh button. Make sure you have included its related scripts too:
  - Add required files using the NPM. To do it add [package.json](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.TestWebApp.V3x/package.json#L14-L17) file and then run the `npm install` command
  - It's better to [bundle](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.TestWebApp.V3x/DNTCaptcha.TestWebApp.V3.csproj#L18) the installed dependencies using `dotnet bundle` [bundleconfig.json](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.TestWebApp.V3x/bundleconfig.json#L17)
  - Or you can download it from: https://github.com/aspnet/jquery-ajax-unobtrusive/releases

**Comment by kajaljain** [comment]
Yes, I installed below packages --

    <PackageReference Include="Microsoft.jQuery.Unobtrusive.Ajax" Version="3.2.6" />
    
    <PackageReference Include="Microsoft.jQuery.Unobtrusive.Validation" Version="3.2.11" />
  
    <PackageReference Include="jQuery" Version="3.4.1" />
    <PackageReference Include="jQuery.Validation" Version="1.19.1" />

**Comment by VahidN** [comment]
After that you should add them [to your _Layout file](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.TestWebApp.V3x/Views/Shared/_Layout.cshtml#L16).
```xml
<script src="~/js/site.min.js" type="text/javascript" asp-append-version="true"></script>
```
Here `/js/site.min.js` is the minified version of all of the [mentioned scripts](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.TestWebApp.V3x/bundleconfig.json#L17) in one file.
You should minify these scripts with this order
```
"node_modules/jquery/dist/jquery.min.js",
"node_modules/jquery-validation/dist/jquery.validate.min.js",
"node_modules/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js",
"node_modules/jquery-ajax-unobtrusive/dist/jquery.unobtrusive-ajax.min.js",
"node_modules/bootstrap/dist/js/bootstrap.min.js"
``` 
And then add the final result to your layout file.

**Comment by caw-ishikajain** [comment]
I tried both ways still not working. 

![image](https://user-images.githubusercontent.com/55681862/84599562-877f1e00-ae90-11ea-96c3-d16ab8f7867b.png)

![image](https://user-images.githubusercontent.com/55681862/84599583-b6958f80-ae90-11ea-9879-246c7ad8d243.png)

**Comment by VahidN** [comment]
Check out the debug output window and also the developers tools -> network tab of your browser to see if there are any errors?

**Comment by caw-ishikajain** [comment]
I am getting below error on click
![image](https://user-images.githubusercontent.com/55681862/84624176-8389e500-aefe-11ea-816d-b9142642a0c9.png)

Also, below error occurs on load
![image](https://user-images.githubusercontent.com/55681862/84624228-9c929600-aefe-11ea-9b55-8b121b000e41.png)

**Comment by kajaljain** [comment]
I am getting below errors
![image](https://user-images.githubusercontent.com/33845598/84630381-79b9af00-af09-11ea-8aba-2610c574574e.png)

**Comment by VahidN** [comment]
[This CSP works here](https://github.com/VahidN/DNTIdentity/blob/master/src/ASPNETCoreIdentitySample.Common/WebToolkit/ContentSecurityPolicyMiddleware.cs#L35).
