### ISSUE TITLE
Auto-refresh after waiting few minutes do not work.

### ISSUE THREAD

**Issue by kajaljain** [VahidN/DNTCaptcha.Core#55]
# Summary of the issue
Refresh work when I click on the refresh button but after waiting for a few mins the image is still the same, and even I try to enter expected output as per the current image displayed it shows an invalid message. 

## Environment

```
DNTCaptcha.Core version: 2.3.0
.NET Core SDK version: 3.0
```

**Comment by VahidN** [comment]
True, It has an expiration date. The image and its related data are not valid forever and it shouldn't be for security reasons.

**Comment by kajaljain** [comment]
Then it should throw some error like a timeout. How can I identify it?

**Comment by VahidN** [comment]
You will always receive `return BadRequest()` or status-code=400. In this case, tell the users to enter the data again or refresh the image again or show them a countdown counter for 7 minutes. A user should be able to login after 7 minutes!

**Comment by kajaljain** [comment]
But when we enter the invalid data then as well we get 400 with an error message, 
I am using the below attribute. How can I differentiate?
        ```
[ValidateDNTCaptcha(
            ErrorMessage = "Please enter the valid sum of digits as a number.",
            CaptchaGeneratorLanguage = Language.English,
            CaptchaGeneratorDisplayMode = DisplayMode.SumOfTwoNumbers)]
```

**Comment by VahidN** [comment]
You can't.
