### ISSUE TITLE
showdigit

### ISSUE THREAD

**Issue by hosseinhagh66** [VahidN/DNTCaptcha.Core#56]
# Summary of the issue

با سلام هنگامی که بر روی تولید عدد قرار میدهیم بیش از 3 حرف را ویرگول قرار میدهد امکان حذف ویرگول وجود دارد؟

ظاهرا مربوط به فرمت متن میباشد
## Environment

```
DNTCaptcha.Core version: 
.NET Core SDK version: 
IDE: 
```

## Example code/Steps to reproduce:

```
 public string GetText(long number, Language language)
        {
            var text = string.Format(CultureInfo.InvariantCulture, "{0:N0}", number);
            return language == Language.Persian ? text.ToPersianNumbers() : text;
        }
```

## Output:

```
Exception message:
Full Stack trace:
```

**Comment by VahidN** [comment]
<div dir="rtl">

سلام؛ خیر. وجود سه رقم جدا کننده کمک حالی است برای خواندن آن

**Comment by Moosapoor** [comment]
سلام. متاسفانه این مساله بارها باعث ایجاد سوال و مشکل از سمت کاربران سایت شده است. بعضی از آنها اصرار بر وارد کردن این علامت دارند و حتی کلید کاما را در صفحه کلید پیدا نمی کنند. اگر این قابلیت هم به صورت option در تگ اضافه شود عالیست

**Comment by ni-fara** [comment]
بله، به نظر میرسه این قابلیت غیر ضروی باشه. چون با اطلاعات مالی سر و کار نداریم که جدا کننده اعداد بحث خوانایی داشته باشه. بلکه کاربر بیشتر این مد نظرش هست که اون چیزی رو که میبه وارد کنه، که خب ویرگول هم جزوش هست و به اشتباه میافته.

**Comment by VahidN** [comment]
Added it via #https://github.com/VahidN/DNTCaptcha.Core/commit/e5e0a9e5f7c9efeec7b54d5578e8a5bd6d788839#diff-8b5fe68f4c03bed7c1c322cc379374d5R36
