### ISSUE TITLE
Change font in captcha phrase

### ISSUE THREAD

**Issue by mohammad68a** [VahidN/DNTCaptcha.Core#57]
Hello
I can't define new font for captcha, and always read that from system fonts
`asp-font-name="Vazir"` not worked actually, although this font existed in styles and appended to my project.
where we can set new font?

**Comment by VahidN** [comment]
Ask your hosting provider to install that font for you. If it's Windows, that font must be installed in `C:\Windows\Fonts` dir.

**Comment by mohammad68a** [comment]
Is it possible to define new custom font from c# code, like EPPlus library?

**Comment by VahidN** [comment]
Added it via#https://github.com/VahidN/DNTCaptcha.Core/commit/b36a88bedb6b53b0dc6475ab6d2190895c3ebec0#diff-2da353640864f13479aa36dfd3e7057eR56
