### ISSUE TITLE
an option to explicitly specify the http/https protocol for captcha image link generation (useful behind reverse proxies)

### ISSUE THREAD

**Issue by mrmashal** [VahidN/DNTCaptcha.Core#59]
# Summary of the issue

I understand that you have used `Request.Scheme` to generate the captcha image link, but this might not be effective behind reverse-proxies or load-balancers where the incoming https traffic is transformed into http to reach the application. Since this can result in "mixed content" warnings in modern browsers, I think some handy option like "PublicOrigin", [as accomplished by the IdentityServer team](https://leastprivilege.com/2017/10/09/new-in-identityserver4-v2-simplified-configuration-behind-load-balancers-or-reverse-proxies/), would make everyone happy:)

## Environment

```
DNTCaptcha.Core version: 2.6.0
.NET Core SDK version: 3.1
IDE: VS2019
```

**Comment by VahidN** [comment]
Are you using [Forwarded Headers Middleware](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-3.1#forwarded-headers-middleware-order) for this case?

**Comment by mrmashal** [comment]
That was a suggestion for a quick and definitive solution to the issue without going through the hassle of such configurations for different setups. If you think it's not worth it feel free to close this.
Thank you so much for your attention
