### ISSUE TITLE
Captcha not work on macOS and docker

### ISSUE THREAD

**Issue by saeedmsdi** [VahidN/DNTCaptcha.Core#6]
I used DNTIdentityCore and got 2 different error on macOs and Docker.

On macOs(latest Mono Installed already) : 

`Exception: The type initializer for 'System.Drawing.KnownColors' threw an exception.</h1>   at System.Drawing.KnownColors.FromKnownColor(KnownColor kc)
   at System.Drawing.ColorConverter.StaticConvertFromString(ITypeDescriptorContext context, String s, CultureInfo culture)
   at System.Drawing.ColorConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.Drawing.ColorTranslator.FromHtml(String htmlColor)
   at DNTCaptcha.Core.Providers.CaptchaImageProvider.DrawCaptcha(String message, String foreColor, String backColor, Single fontSize, String fontName)
   at DNTCaptcha.Core.DNTCaptchaImageController.Show(String text, String rndDate, String foreColor, String backColor, Single fontSize, String fontName)`

And on Docker (USE microsoft/aspnetcore-build:1.1.1) : 

`info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method DNTCaptcha.Core.DNTCaptchaImageController.Show (DNTCaptcha.Core) with arguments (CfDJ8AUyVhOCtYhBqsBayGrsMEg6ZEKonj8Yu4zyLjktNB8GB1aWxuLw9zhe3cuRfPfMiOi/F2sTu/8TXeYBrtMG42XJ2TPsiPDrmOU19aetv6kfg+YXpQu7Jy3vFg1RG3I9gY0ugsP2zH5Cb5uu15Zr50A=, 636275045063773290, black, #ccc, 20, Tahoma) - ModelState is Valid
info: Microsoft.AspNetCore.Mvc.StatusCodeResult[1]
      Executing HttpStatusCodeResult, setting HTTP status code 400
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action DNTCaptcha.Core.DNTCaptchaImageController.Show (DNTCaptcha.Core) in 0.3593ms
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method IdentityServerWithIdentityCore.Controllers.ErrorController.Index (IdentityServerWithIdentityCore) with arguments (400) - ModelState is Valid
fail: IdentityServerWithIdentityCore.Controllers.ErrorController[0]
      Error 400 for GET /DNTCaptchaImage/Show
      
      Accept: image/png,image/svg+xml,image/*;q=0.8,*/*;q=0.5
      Accept-Encoding: gzip, deflate
      Accept-Language: en-us
Cookie: .AspNetCore.Antiforgery.c0metC3jpAQ=CfDJ8AUyVhOCtYhBqsBayGrsMEgQPLfXuennB5AZ9tcxb05LRvGuolVy-ESXwrTXZXhAoBPp-........`

**Comment by saeedmsdi** [comment]
For testing docker I use https://dashboard.abarcloud.com/console ,it's on linux container

**Comment by VahidN** [comment]
To run this project on Linux, you will need to install libgdiplus too:
```
sudo apt-get update
sudo apt-get install libgdiplus
```
For MacOS here: https://github.com/CoreCompat/CoreCompat/issues/3

**Comment by saeedmsdi** [comment]
@VahidN thanks it works for me on Docker.
Bot I have a problem on characters like this :  
![screen shot 1396-01-27 at 13 13 38](https://cloud.githubusercontent.com/assets/3229325/25070019/f4eea2a4-22a6-11e7-870f-8499662ce699.png)

**Comment by VahidN** [comment]
You can try setting different fonts here
```xml
asp-font-name="Tahoma"
asp-font-size="20"
```

**Comment by saeedmsdi** [comment]
I have problem with font changes too. 

`The requested FontFamily could not be found [GDI+ status: FontFamilyNotFound]`

I'd work on it a few days on OSX and Docker but I think CoreCompact have problem with linux, osx and docker, based on [this section](https://github.com/CoreCompat/CoreCompat#running-systemdrawing-for-net-core-on-os-x-or-linux) even with packages proposed by CoreCompact.

If you wish ,try [this project](https://github.com/JimBobSquarePants/ImageSharp). I think it's much cross-platform or a better one.

Thanks again,

**Comment by VahidN** [comment]
Try V1.4.1
```
 dotnet add package DNTCaptcha.Core --version 1.4.1 
```
It uses the official `System.Drawing.Common` of Microsoft for .NET Core 2.x.

**Comment by hmdhasani** [comment]
same error on nanoserver in windows based container

**Comment by AlirezaSalimi1** [comment]
I have the same character problem and changing font did not help
I'm using ASP Core 1.1 and migrating to ASP Core 2 is not possible for me now
Is there any workaround available for me?

**Comment by AlirezaSalimi1** [comment]
I have the same character problem and changing font did not help
I'm using ASP Core 1.1 and migrating to ASP Core 2 is not possible for me now
Is there any workaround available for me?

**Comment by VahidN** [comment]
No. This `System.Drawing` package is out of my control. follow its issues here:
https://github.com/CoreCompat/CoreCompat/issues/3
