### ISSUE TITLE
Use DNTCaptcha in Separated Service

### ISSUE THREAD

**Issue by aramdata** [VahidN/DNTCaptcha.Core#60]
# Summary of the issue

با سلام ، به دلیل وجود GetSalt 
امکان ایجاد کپچا توسط درخواست کاربر بامرورگر و درخواست  اعتبار سنجی آن توسط یک اپلیکیشن دیگر وجود ندارد آیا امکان دارد که این کپچا بصورت یک سرویس مستقل فقط وظیفه ایجاد و اعتبار سنجی (درخواست از سرویس های دیگر) کپچا را داشته باشد؟

**Comment by VahidN** [comment]
If you want to use it in a single page apps or without MVC(and its views), follow this sample:
- [A sample .html file](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.TestApiApp/wwwroot/index.html)
- [A sample API controller](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.TestApiApp/Controllers/AccountController.cs)

**Comment by aramdata** [comment]
<div dir="rtl">
با UseCustomStorageProvider 
این مسئله حل شد ، فقط آیا نبود ip ، user agent باگ منطقی و امنیتی خاصی ایجاد میکنه ؟
</div>
