### ISSUE TITLE
header is too long

### ISSUE THREAD

**Issue by oaww** [VahidN/DNTCaptcha.Core#61]
# Summary of the issue

Bad Request - Request Too Long
HTTP Error 400. The size of the request headers is too long.

it has chance to occur,when refresh the captcha

**Comment by VahidN** [comment]
You can use other `StorageProvider`s which are not based on HTTP headers, such as MemoryCache, etc.

  services.AddDNTCaptcha(options =>
                // options.UseSessionStorageProvider() // -> It doesn't rely on the server or client's times. Also it's the safest one.
                // options.UseMemoryCacheStorageProvider() // -> It relies on the server's times. It's safer than the CookieStorageProvider.
                options.UseCookieStorageProvider() // -> It relies on the server and client's times. It's ideal for scalability, because it doesn't save anything in the server's memory.
                // options.UseDistributedCacheStorageProvider() // --> It's ideal for scalability using `services.AddStackExchangeRedisCache()` for instance.

                // .UseCustomFont(Path.Combine(_env.WebRootPath, "fonts", "name.ttf"))
                // .AbsoluteExpiration(minutes: 7);
                );
