### ISSUE TITLE
Visual Studio Version?

### ISSUE THREAD

**Issue by michelcedric** [VahidN/DNTCaptcha.Core#64]
# Summary of the issue

I want to compile, and why not contribute but impossible to build your project

![image](https://user-images.githubusercontent.com/7223553/97115545-87711380-16f7-11eb-8ac0-99b99b1bef45.png)

**Comment by VahidN** [comment]
It requires [.NET Core SDK 3.1.402](https://github.com/VahidN/DNTCaptcha.Core/blob/master/global.json#L3) or higher. You will need [VS 2019](https://github.com/dotnet/announcements/issues/108) for it. 

P.S.
I only have VSCode + its C# plugin installed my system + .NET Core SDK.

**Comment by michelcedric** [comment]
Hi @VahidN 
I forgot to update the .net core version 
Thanks ;)
