### ISSUE TITLE
HTTP/1.1 400 Bad Request 

### ISSUE THREAD

**Issue by Rezasalami** [VahidN/DNTCaptcha.Core#65]
# Summary of the issue
on iis server can't load pic 
sample  url
https://xxxx.ir/dntcaptchaimage/show?data=CfDJ8BJLCCEzvSdCrnGsfblcVjL_k-aeuVKobRSAr3Dn1P7MX31ByyZ0XM0sjaBZbpaKU9AdNg0tTYEq9CDjcKdro7VKCIQWcDJYQQkWXAZQ5h_edUKael75k_5v6XjlsZbNHsCo89PF7v5GARB_WNq9_SaO83qe93ilvuUeBZwQ5lU0FX_rByWc

## Environment

```
DNTCaptcha.Core version: 2.8
.NET Core SDK version: 5
IDE: vscode
```

## Example code/Steps to reproduce:
I use your sampel code
Razor page
this working on local by vs 2019 
```
paste your core code
```

## Output:

```
Exception message:
Full Stack trace:
```

**Comment by VahidN** [comment]
don't use it. thnx.
