### ISSUE TITLE
مشکل با اعداد فارسی در سیستم عامل اندروید

### ISSUE THREAD

**Issue by rezaeiy** [VahidN/DNTCaptcha.Core#7]
سلام و عرض ادب
مشکلی که من باهاش برخورد کردم اینه که زمانیکه از طریق گوشی اندروید ارقام رو وارد میکنم اگه صفحه کلید در حالت فارسی باشه جواب نمیده(از عدد وارد شده خطا میگیره که با رشته عددی برابر نیست) ولی در حالت انگلیسی مشکلی نداره
با تشکر

**Comment by VahidN** [comment]
Fixed via https://github.com/VahidN/DNTCaptcha.Core/commit/8dc8cee5f84d48be379ab5eec2a5a0c84bea9d25
```
PM> update-package
```
