### ISSUE TITLE
cookieValue IsNullOrWhiteSpace

### ISSUE THREAD

**Issue by rezaeiy** [VahidN/DNTCaptcha.Core#8]
سلام جناب نصیری
وقتتون بخیر
توی قسمت لاگ پروژه 
asp.net identity core
خطا و هشدار زیر بسیار رخ می دهد.
![w0](https://user-images.githubusercontent.com/4429723/28458397-dacdbaf4-6e1e-11e7-9989-3d29cd5c1266.JPG)
![w1](https://user-images.githubusercontent.com/4429723/28458404-dff94926-6e1e-11e7-918f-5d66ff704b18.JPG)
![w3](https://user-images.githubusercontent.com/4429723/28458411-e5324762-6e1e-11e7-8e8f-32205be4296f.JPG)

ممنون میشم راهنمایی بفرمایید دلیل رخ دادن موارد ذکر شده چیست
با تشکر

**Comment by VahidN** [comment]
<div dir="rtl">
در كل اين خطا به اين معنا است كه درخواستي به سرور رسيده اما حاوي كوكي نيست.
ممكن است سايت توسط يك سري بات بررسي شده باشد و درخواست ارسالي آن‌ها به سرور حاوي كوكي نباشد
