### ISSUE TITLE
option to remove captcha from storage if validation failed

### ISSUE THREAD

**Issue by kot-pilot** [VahidN/DNTCaptcha.Core#80]
Is there any posibility to easy achive removing captcha from storage on validation fail (as I understand for now it only removes captcha if validation passed, or after timeout) ? or maybe it will be introduced in some next release?

**Comment by VahidN** [comment]
It always will be removed during [the first GetValue](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.Core/SessionCaptchaStorageProvider.cs#L75).
