### ISSUE TITLE
dotnettips.info

### ISSUE THREAD

**Issue by GhalamborM** [VahidN/DNTCaptcha.Core#84]
سلام
وقت‌تون بخیر
سایت dotnettips.info
چند روزی میشه فعال نیست
اگر کمکی از دست کسی بر میاد اعلام کنید
مطمئنا شما و اون سایت به خیلی‌ها کمک کردید 
و بهترین مرجع برای توسعه دهنده‌های فارسی زبان هستش
ان‌شا‌الله که مجددا فعال بشه

**Comment by VahidN** [comment]
<div dir="rtl">

سلام؛ متاسفانه به علت زورگويي جماعت آمريكايي تمام سايت‌هاي ايراني داراي دومين‌هاي .info معلق شدند
آدرس جديد سايت: https://www.dntips.ir
