### ISSUE TITLE
حذف نشدن کوکی ها

### ISSUE THREAD

**Issue by mohsen2hasani** [VahidN/DNTCaptcha.Core#9]
سلام، روزتون بخیر
با هر بار لود شدن صفحه یک کوکی ساخته شده و به هیچ وجه حذف نمیشوند و باعث میشود حجم ریکوئست ها بالا رفته و پس از چندین بار وارد کردن اشتباه کپچا، کاربر دیگر قادر به مشاهده سایت نباشد
(**Bad Request - Request Too Long**)

![screenshot 2](https://user-images.githubusercontent.com/8465431/30509363-37c65582-9ac4-11e7-93ab-eac1f6ebb6a2.png)

**Comment by mohsen2hasani** [comment]
به نظرم اگه زمان ایجاد شدن کوکی، تمام کوکی هایی که با 10 کاراکتر اول کوکی مورد نظر هستن پاک بشن، مشکل میتونه حل بشه
`        public void Add(HttpContext context, string token, string value)
        {
            foreach (var cookie in context.Request.Cookies.Keys)
            {
                if (cookie.Contains(token.Substring(0, 10)))
                    context.Response.Cookies.Delete(cookie);
            }
            value = _captchaProtectionProvider.Encrypt($"{value}{getCookieValueSalt(context)}");
            context.Response.Cookies.Append(token, value, getCookieOptions(context));
        }`

**Comment by VahidN** [comment]
<div dir="rtl">
طول عمر كوكي‌ها، تنظيم شده به سشن كاربر هست. يعني همينقدر كه مرورگر بسته شود، اين كوكي‌ها هم پاك مي‌شوند

شما احتمالا در حال آزمايش برنامه هستيد و هنوز مرورگر خودتان را نبسته‌ايد تا سشن آن تمام شود. بنابراين مساله‌ي خاصي نيست.
