### ISSUE TITLE
Unseal ValidateDNTCaptchaAttribute

### ISSUE THREAD

**Issue by jchadwick** [VahidN/DNTCaptcha.Core#91]
# Summary of the issue
I am having trouble understanding why `ValidateDNTCaptchaAttribute` is sealed.  

I want to use CAPTCHA in several pages using the same settings, however since the attribute is sealed I am unable to derive from it and therefore it seems I have to explicitly set all of the settings (and keep them in sync) on every action.

## Environment
N/A

## Example code/Steps to reproduce:

```
    public class ValidateCaptchaAttribute : ValidateDNTCaptchaAttribute
    {
    }
```

## Output:

```
Cannot derive from sealed type ValidateDNTCaptchaAttribute
```

**Comment by VahidN** [comment]
Try V 3.7
