### ISSUE TITLE
only on server Status Code: 400 Bad Request, .net core5.0  

### ISSUE THREAD

**Issue by m3mara** [VahidN/DNTCaptcha.Core#96]
# Summary of the issue
i'm trying to use DNTCaptcha.Core with Razor page .net core5.0
working fine on localhost, but after publish it to serever captch image is not displayed

## Environment

```
DNTCaptcha.Core version: 3.5.0
.NET Core SDK version: 5.0
IDE: chrome
```

## Example code/Steps to reproduce:

```
paste your core code
```
html
---------------------------Page.cshtml---------------------------
       dnt-captcha
 asp-captcha-generator-max="999999"
                                 asp-captcha-generator-min="111111"
                                 asp-captcha-generator-language="English"
                                 asp-captcha-generator-display-mode="ShowDigits"
                                 asp-use-relative-urls="true"
                                 asp-placeholder="@enterCode"
                                 asp-validation-error-message="@codeError"
                                 asp-font-name="Tahoma"
                                 asp-font-size="20"
                                 asp-fore-color="#333333"
                                 asp-back-color="#8a7500"
                                 asp-text-box-class="text-box form-control"
                                 asp-text-box-template="<span class='input-group-prepend'><span class='form-group-text'></span></span>{0}"
                                 asp-validation-message-class="text-danger"
                                 asp-refresh-button-class="fa fa-refresh code-refresh"
                                 asp-use-noise="false" 
---------------------------Page.cshtml---------------------------

------------------------_ViewImports.cshtml-------------------------
@addTagHelper *, DNTCaptcha.Core
------------------------_ViewImports.cshtml-------------------------

C#
------------------------Page Model-------------------------
        private readonly IDNTCaptchaValidatorService _validatorService;
        private readonly DNTCaptchaOptions _captchaOptions;
------------------------Page Model-------------------------

------------------------Startup.cs-------------------------
services.AddDNTCaptcha(options =>     
            options.UseCookieStorageProvider()     
            .ShowThousandsSeparators(false));
------------------------Startup.cs-------------------------

## Output:
Request URL: https://dimain.com/DNTCaptchaImage/Refresh?data=3pldrU0evLFL8tRgwvbGn9RiR-rkao5OnW0CeE7ImI628BkvYlDSw9u1uO4-q7aHXQ2RRaMwvTxN3fblIETmbKKy1RS9BpOL
Request Method: POST
Status Code: 400 Bad Request

```
Exception message:
Full Stack trace:
```

**Comment by roomak** [comment]
Hi Dear Vahid,
I have the same problem on my server, It looks like sends the request from the client twice when the 400 error occurs after that

![image](https://user-images.githubusercontent.com/32766075/111141589-f6f97980-8598-11eb-88a3-8d0135dfc45a.png)

**Comment by VahidN** [comment]
If you are using the `cookie storage` and you have problem with the [SameSite](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.Core/CookieCaptchaStorageProvider.cs#L114) setting try other storage's [such as the cache or session providers](https://github.com/VahidN/DNTCaptcha.Core/blob/master/src/DNTCaptcha.TestWebApp/Startup.cs#L51).
